app/api/urls.py
from django.urls import path
from . import views
from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView
from django.urls import path, include
from	rest_framework.routers import	DefaultRouter


router = DefaultRouter()
from api.views import MessageViewSet, TaskViewSet,TeamViewSet, UserProfileViewSet
router.register("messages", MessageViewSet)
router.register('tasks', TaskViewSet)
router.register('team', TeamViewSet)


urlpatterns = [

     path("jwt/", TokenObtainPairView.as_view(), name="jwt_obtain_pair"),
     path("jwt/refresh/", TokenRefreshView.as_view(), name="jwt_refresh"),
     path('checkAuth/', views.checkAuth.as_view({'get': 'get'}), name='checkAuth'),
     path("home/", views.Homeview.as_view({'get': 'retrieve'}), name="home"),
     path('team/', views.TeamViewSet.as_view({'get':'list'}), name ='team'),
     path('activate/task/<int:pk>', views.ActivateTask.as_view(),name='activate'),
     path('subtasks/<int:pk>/', views.SubtaskViewSet.as_view({
                                     'post':'create', 'patch':'update'}), name="subtasks"),

     path('subtasks/completed/<int:pk>/', views.SubtaskCompleted, name="subtask_completed"),
     path('upload/', views.ImageUploadView.as_view(), name='upload'),
     path('upload/file/<int:pk>', views.FileUploadView.as_view(), name='uploadFiles'),
     path('chat/', views.ChatViewSet.as_view({'get':'get'}), name='chat'),
     path('chat/submit/', views.SaveMessage.as_view({'post':'post'}), name='savemsg'),
     path('loading/<str:celery_id>/<str:photo>/', views.Ready.as_view({'get': 'get'}), 
          name='ready'),
    # path('messages/unread', views.UnreadMessages.as_view(), name='unread_count'),
     path('profile/', views.UserProfileViewSet.as_view({'get':'retrieve'})),
     path('pushtoken/', views.RegisterPush.as_view(), name='registerpush'),
     path("",	include(router.urls)),

     #path('home')
]

app/dashboard/urls.py
from . import views
from django.urls import path
from .forms import CustomPasswordChangeForm, ProfileUpdateForm


app_name = 'dashboard'
urlpatterns = [
    
    ####### Users , Home#########
    path('options/', views.setOptions, name='options'),
    path('loading/<str:celery_id>/<str:type>/<int:object_id>/<str:arg>', 
         views.LoadingView.as_view(), name= 'loading'),
    path('loading/ready/<str:celery_id>/<str:type>/<int:object_id>/<str:arg>', 
         views.Ready, name='ready'),
         
    path('home/', views.BillboardView.as_view(), name = 'home'),
    path('logout/', views.LogoutView.as_view(), name ='logout'),
    path('report/', views.ReportView.as_view(), name='report'),
    path('role_dispatch/', views.role_dispatch, name='role_dispatch'),
    path('account/<int:pk>', views.AccountView.as_view(), name='user_account'),
    path('account/update/<int:pk>', views.AccountUpdate.as_view(form_class=ProfileUpdateForm),
     name='account_update'),
    path('account/update/password/<int:pk>', views.PasswordChangeView.as_view(
        form_class=CustomPasswordChangeForm), name="password_update"),
 
    ####### Messages ##########
    path('messages/reply/create/<int:recipient_id>', views.ReplyView.as_view(),
          name="message_reply"),
    path('messages/', views.HomeView.as_view(), name='messages'),
    path('messages/create/', views.MessageView.as_view(), name = 'messages_create'),
    path('messages/forward/<int:pk>', views.MessageForward.as_view(), name='message_forward'),
    path('report_detail/<int:id>/', views.MessageDetail.as_view(), name='reportview'),
    path('messages/inbox', views.InboxView.as_view(), name = 'inbox'),
    path('delete_report/<int:pk>', views.MessageDelete.as_view(), name = 'report_delete'),
    path('update_report/<int:pk>', views.MessageUpdate.as_view(), name = 'report_update'),
    ##########TASKS#########
    path('tasks/<int:pk>/activate', views.setActiveTask, name='activate_task'),
    path('tasks/subtask/<int:pk>', views.FetchSubtask, name='fetch_subtask'),
    path('tasks/<int:task>/subtask/<int:pk>', views.SubtaskCompleted, name="subtask_completed"),
    path('tasks/', views.TasksList.as_view(), name = 'tasks_list'),
    path('tasks/<int:pk>/', views.TaskDetail.as_view(), name='task_detail'),
    path('tasks/delete/<int:pk>', views.TaskDelete.as_view(), name = 'task_delete'),
    path('tasks/completed/<int:pk>', views.TaskSubmit.as_view(), name='task_submit'),
    ######### Files #########
    path('pic_picture/<int:pk>', views.stream_file, name='pic_picture'),
    path('pic_picture_completed_task/<int:pk>', views.stream_completed_task_img, 
         name='stream_completed_task_img'),
    path('file/<int:pk>/download', views.GetFile, name="get_file"),
    path('report/<int:pk>/download', views.getReport, name='get_report'),
    path('file/<int:pk>/task/delete/<int:manage>', views.DelFile, name='delete_file'),
    path('resource/<int:pk>', views.getResource, name='get_resource'),
    ####### MANAGE ###########
    path('team/', views.TeamView.as_view(), name = 'team'),
    path('tasks/completed/<int:pk>/', views.TaskCompletedDetail.as_view(), name='task_completed_detail'),
    path('tasks/create/', views.TaskManageCreate.as_view(), name = 'task_manage_create'),
    path('tasks/update/<int:pk>', views.TaskUpdate.as_view(), name = 'task_manage_update'),
    path('tasks/completed/approve/<int:pk>', views.TeamCompletedApprove.as_view(), 
         name = 'task_approve'),
    path('tasks/history/', views.TaskHistoryView.as_view(), name='task_history'),
    path('team/ressources', views.RessourcesView.as_view(), name="ressources"),
    path('team/getSection/<int:chart>', views.getSection, name='get_section'),



    ####### SCHEDULES ########
    path('schedules', views.ScheduleView.as_view(), name = 'schedule_view'),
    path('schedules/<int:pk>', views.ScheduleDetail.as_view(), name = 'schedule_detail'),
    path('schedules/manage', views.ScheduleManage.as_view(), name = 'schedule_manage'),
    path('schedules/update/<int:pk>', views.ScheduleUpdate.as_view(), 
         name = 'schedule_update'),
    path('schedules/user/<int:pk>/availability', views.AvailabilityForm.as_view(), 
         name='availability'),
    path('schedules/user/<int:pk>/request', views.ScheduleChangeRequest.as_view(),
          name='schedule_request'),
 
    #######TEAM ##########
    path('team/update/<int:pk>', views.TeamUpdate.as_view(), name='team_update'),
    path('team/completed/', views.TeamCompletedTask.as_view(), name='team_completed'),
    path('team/user/<int:pk>/stats', views.PerformanceDetail.as_view(), name = 'perf_detail'),
    path('team/<int:pk>/stats', views.PerformanceView.as_view(), name = 'perf_team'),
    path('team/<int:pk>/stats/page/<int:page>', views.PerformanceView.as_view(),
         name='perf_team_detail'),


    ####### Milestones ########
  
    path('history/milestones/team/<int:pk>', views.HistoryView.as_view(), name='history_view'),
    path('team/vs_team', views.TeamVs.as_view(), name="team_vs"),
    
    #######PROJECTS ######
    path('projects', views.ProjectsView.as_view(), name='projects'),
    path('projects/chart/<int:pk>', views.ChartDetail.as_view(), name='chart_detail'),
    path('projects/chart/create', views.ChartCreate.as_view(), name = "chart_create" ),
    path('projects/chart/load/<int:pk>', views.LoadChart, name="load_chart"),
    path('projects/chart/create/add_section/<int:pk>', views.AddSection.as_view(), name="add_section"),
    path('projects/chart/<int:pk>/create/task', views.ChartTaskCreate.as_view(),
          name='create_task_chart'),
    path('projects/chart/<int:chart>/task/<int:pk>/update', views.ChartTaskUpdate.as_view(), name='chart_task_update'),
    path('projects/chart/<int:pk>/update', views.ChartUpdate.as_view(), name='chart_update'),
    path('projects/chart/sections/delete/<int:pk>', views.SectionDelete, name='sections_update'),
    path('projects/chart/<int:pk>/delete', views.ChartDelete.as_view(), name ='chart_delete'),
    path('projects/chart/<int:pk>/reset', views.ChartReset, name='reset_chart'),
    #path('projects/chart/save/<int:pk>', views.SaveChart, name='chart_save'),
    path('projects/chart/<int:task_id>/<int:section_id>/<int:chart_id>/<str:prev>/<str:next>', 
         views.SwapTask, name='swapTask'),
    ######CHAT##########
    path('chat', views.ChatView.as_view(), name='chat_view'),
    path('chat/update/', views.ChatUpdate, name='chat_update'),

] 

app/portal/urls.py
from django.contrib import admin
from django.shortcuts import redirect
from django.urls import path, include, reverse
from dashboard.views import CustomLoginView
from dashboard.views import CustomRegistration
from dashboard.forms import CustomRegistrationForm
from django.conf.urls.static import	static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/' ,include('api.urls')),
    path('accounts/register/',
        CustomRegistration.as_view(form_class=CustomRegistrationForm),
        name='django_registration_register'),

    path("accounts/", include("django_registration.backends.one_step.urls")),
    path("accounts/", include("django.contrib.auth.urls")),
    path('dashboard/', include('dashboard.urls', namespace='dashboard')),
    path('', CustomLoginView.as_view(template_name='dashboard/login.html')),
    path('__debug__/', include('debug_toolbar.urls')),

]
urlpatterns+= static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns+= static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

app/dashboard/templates/dashboard/base.html
<!DOCTYPE html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Dashboard</title>
     {% load static %}
     <link rel="stylesheet" href="{% static 'dashboard/team_vs.css' %}">
     <link rel="stylesheet" href="{% static 'dashboard/home.css' %}">
     <link rel="stylesheet" href="{% static 'dashboard/messages.css' %}">
     <link rel="stylesheet" href="{% static 'dashboard/msg_main.css' %}">
     <link rel="stylesheet" href="{% static 'dashboard/tasks.css' %}">
     <link rel="stylesheet" href="{% static 'dashboard/team.css' %}">
     <link rel="stylesheet" href="{% static 'dashboard/management/management.css' %}">
     <link rel="stylesheet" href="{% static 'dashboard/management/tasks.css' %}">
     <link rel="stylesheet" href="{% static 'dashboard/management/schedules.css' %}">
     <link rel="stylesheet" href="{% static 'dashboard/management/history.css' %}">
     <link rel="stylesheet" href="{% static 'dashboard/chat.css' %}">
     <link rel="stylesheet" href="{% static 'dashboard/inbox.css' %}">
     <link rel="stylesheet" href="{% static 'dashboard/charts.css' %}">
     <link rel="stylesheet" href="{% static 'dashboard/schedules.css' %}">
     <link rel="stylesheet" href="{% static 'dashboard/account.css' %}">
     <link rel="stylesheet" href="{% static 'dashboard/history.css' %}">
     <link rel="stylesheet" href="{% static 'dashboard/resources.css' %}">
     <link rel="stylesheet" href="{% static 'dashboard/reports.css' %}">
     <link rel="stylesheet" href="{% static 'dashboard/base/base.css' %}">

    <script src="https://cdn.jsdelivr.net/npm/inputmask@5.0.9/dist/inputmask.min.js"></script>

     <script src="{% static 'js/getSubtask.js' %}"></script>
     
     {% block extra_css %}
     {% endblock %}

</head>

<body>

<div class="nav_container"> 
<nav class="nav_top">
  
  <a href="{% url 'dashboard:home' %}">Home</a>
  <a href="{% url 'dashboard:messages' %}">Messages</a>
  {% if new > 0 %}<div class="new_msg_count_div">{{new}}</div>{% endif %}
  <a href="{% url 'dashboard:tasks_list' %}">Tasks</a>
  <a href="{% url 'dashboard:projects' %}">Projects</a>
   
  <a href="{% url 'dashboard:team' %}">Team</a>

  <a href="{% url 'dashboard:chat_view' %}">Chat</a>
  <button onclick="setVisible(this,'shade_logout')">Logout</button> 
  {% if is_home %}
  <a href="{% url 'dashboard:user_account' user.id %}" class="userprofile_nav">User profile</a>
  {% endif %}


</nav>
</div>
{% load static %}



<div id="shade_logout">
  
<div id="report_modal">

    <div class="logout_x_btn" 
    onclick="document.getElementById('shade_logout').style.display='none'">
    X
    </div>

    <form method="post" action='{% url "dashboard:logout" %}'>
      {% csrf_token %}
       <div class="logout_title">
        Logout ?

       </div> 
        <div class="logout_modal_btn_cont">
          <a href="{% url 'dashboard:report' %}" class="report_btn">
          <button type="button">Do your report</button>
          </a>

          <button type="submit" class="logout_modal_btn"> Logout </button>
       </div>

    </form>
</div>

</div>



{% if user.userprofile.active_task and options.active_task %}

<a href="{% url 'dashboard:task_detail' user.userprofile.active_task.id %}" class="go_to_active">
  Active task
</a> 

{% endif %}
 {% block content %}{% endblock %}


<!--------------------------------NOTIF MODAL---------------------------------------->

<div class="notif_div" id=notif>


       
    
</div>

{% if options.help %}
<a href="{% url 'dashboard:ressources' %}">
 <img src= "{% static 'question_mark.png' %}" id="question_mark">
 </a>
{% endif %}
<script>

const login = '{{options.login}}'
const late  = '{{options.late}}'

const socket = new WebSocket('ws://127.0.0.1:8000/ws/test/');

socket.onopen = () => {
  console.log('WebSocket connection established');
};

socket.onmessage = (event) => {
  const notif = document.getElementById('notif')
  const data = JSON.parse(event.data);
  console.log('Received:', data.message);  
  if (data.message !== 'WebSocket connected'){

    if (data.type == 'message'){


      notif.innerHTML += 
    `
    <div id="notifBubble${data.message.id}" class="notifBubble">
         
      <button class="x_btn_notif" onclick="document.getElementById(
        'notifBubble${data.message.id}').style.display='none'" type="button">X 
      </button> 

      <a href="report_detail/${data.message.id}/">
      <div class="notif_header">
          <img src="{% static 'msg_icon.png' %}" style="width:20%">
          <div class="right_header_notif">
              <div style="margin-left: 1.5vw;">
                New message
              </div>
              <div class="from_text_notif">
                From ${data.message.sender}
              </div>
          </div>
   
      </div>
         
      <div class="notif_content">
          ${data.message.content}
      </div>
      
      
    </div>
    </a>`

    }
    else if (data.type === 'late_notice' && late === 'True'){
       notif.innerHTML += 
      ` <div id="notifBubble${data.message.id}" class="notifBubble">
         
      <button class="x_btn_notif" onclick="document.getElementById(
        'notifBubble${data.message.id}').style.display='none'" type="button">X 
      </button> 
      <div class="notif_header_late">
          <img src="{% static 'exclamation.png' %}" style="width:15%; padding-right: 3vw;">
         Late notice
      </div>
         
      <div class="notif_content_late">
          ${data.message.content}
      </div>
      
      
    </div>`
    }
     else if (data.type === 'star'){
       notif.innerHTML += 
      `  <div id="notifBubble${data.message.starid}" class="notifBubble">
         
      <button class="x_btn_notif" onclick="document.getElementById(
        'notifBubble${data.message.starid}').style.display='none'" type="button">X 
      </button> 
      <a href="/dashboard/account/${data.message.id}">

   
      <div class="notif_header_late">
        <img src="{% static 'star_icon3.png' %}" style="width:12%; padding-right: 4.1vw;">
         New star
      </div>
         
      <div class="notif_content_late">
          You have been awarded a star , go check it out !
      </div>
      
      
    </div>
       </a>`
    }
    else if (data.type === 'milestone') {
       notif.innerHTML += 
          ` <div id="notifBubble${data.message.id}" class="notifBubble">
         
      <button class="x_btn_notif" onclick="document.getElementById(
        'notifBubble${data.message.id}').style.display='none'" type="button">X 
      </button> 
      <a href="/dashboard/account/1">

   
      <div class="notif_header_late">
        <img src="{% static 'trophee.png' %}" style="width:12%; padding-right: 2.7vw;">
         New milestone
      </div>
         
      <div class="notif_content_mile">
          <div style="padding-bottom: 2.5%; padding-top: 2.5%; text-align: center;">
            ${data.message.name}
          </div>
           ${data.message.type} (${data.message.value})
      </div>
      
      
    </div>
       </a>`
    }
    else if (data.type === 'task_submit'){
       notif.innerHTML += 
          ` <div id="notifBubble${data.message.id}" class="notifBubble">
         
      <button class="x_btn_notif" onclick="document.getElementById(
        'notifBubble${data.message.id}').style.display='none'" type="button">X 
      </button> 
      <a href="/dashboard/tasks/completed/${data.message.task_id}/">

   
      <div class="notif_header_task">
        <img src="{% static 'task_icon.png' %}" style="width:12%; padding-right: 2.3vw;">
         Task completed
      </div>
         
      <div class="notif_content_mile">
          <div style="padding-bottom: 2.5%; padding-top: 2.5%; text-align: center;">
           
          </div>
           ${data.message.name}
      </div>
      
      
    </div>
       </a>`
    }
    else if (data.type === 'login' && login === 'True'){
      let task_name = null
      if (data.message.task_name){
         task_name = data.message.task.name
      }
      else {
        task_name = ''
      }

     notif.innerHTML += 
        `  <div id="notifBubble${data.message.id}" class="notifBubble">
         
      <button class="x_btn_notif" onclick="document.getElementById(
        'notifBubble${data.message.id}').style.display='none'" type="button">X 
      </button> 
          <div class="top_login">
          <img src="{% static 'team_icon14.png' %}" style="width: 9%; padding-right: 3.5vw; ">
            Just logged in 
          </div>
      <div class="notif_header_login">
          <a href="/dashboard/team/user/${data.message.user_id}/stats">${data.message.username}</a>
        
      </div>
      <div class="notif_content_login">
        <img src="{% static 'task_icon.png' %}" style="width: 9%;">
        <a href="/dashboard/tasks/update/${data.message.active_task}/">${task_name}</a>
      
      </div>
    </div>`
    }
    else if (data.type === 'report'){

     notif.innerHTML += 
        `  <div id="notifBubble${data.message.id}" class="notifBubble">
         
      <button class="x_btn_notif" onclick="document.getElementById(
        'notifBubble${data.message.id}').style.display='none'" type="button">X 
      </button> 
          <div class="top_report">
           <img src="{% static 'exclamation.png' %}" style="width:15%; padding-right: 2.1vw;">
            Missing report
          </div>
      <div class="notif_header_report">

          It seems like <a href="/dashboard/team/user/${data.message.user_id}/stats">${data.message.username}</a>
          did not make any report this week .
      </div>
     
    </div>`
    }
    else if (data.type === 'task_approval'){
      notif.innerHTML +=
      `      <div id="notifBubble${data.message.id}" class="notifBubble">
         
      <button class="x_btn_notif" onclick="document.getElementById(
        'notifBubble${data.message.id}').style.display='none'" type="button">X 
      </button> 
      <a href="/dashboard/tasks/">

   
      <div class="notif_header_approve">
      
            
            <img src="{% static 'task_icon.png' %}" style="height:70%; ">
           
           <div class="head_text_approve">
              <div style="padding-right: 2vw;"> 
                  Task approval
                  </div>
            
                  <div class="task_approve">
                  Task with a long name that tests bound

                  </div>
          </div>
      </div>
         
      <div class="notif_content_approve">
          <div style="padding-bottom: 2%;">
           
         
          A task was submitted and is pending team approval.
           </div>
      </div>
      
      
    </div>
       </a>   
`
    }

};

socket.onclose = () => {
  console.log('WebSocket connection closed');
};

socket.onerror = (error) => {
  console.error('WebSocket error:', error);
};
}
</script>
</body>

app/dashboard/templates/dashboard/chat_view.html
 {% include 'dashboard/base.html' %}


{% block extra_css %}
<script src="https://cdn.jsdelivr.net/npm/dayjs@1/dayjs.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/dayjs@1/plugin/relativeTime.js"></script>
<style>
    
    html{
        background-color: rgb(128, 107, 88) !important;
    }
</style>
{% endblock %}
{% block content %}
 
<div class="chat_frame"> 
<div class="chat_bg"> </div>
   <div class="chat_container">
    <div class="chat" id="chat"> </div>
   </div>

<div class="chat_form_div">
    <div>
   <form class="chat_form_msg" method="post" id="chat_form">
    {% csrf_token %}
    {{form.message}}
    </div>


    <button class="send_button_chat "type="submit">Send</button>
   


   </form>

  
{% endblock %}


<script>

dayjs.extend(window.dayjs_plugin_relativeTime);

async function update_messages() {


    
    try { 
    const response = await fetch(`/dashboard/chat/update/`)
    const data = await response.json()
    console.log(data);
    
    last = data[0]['id']

    const chatContainer = document.getElementById('chat');
    chatContainer.innerHTML = ''; // clear previous messages
    
    for (var x = 0; x < data.length; x++ ){
 
            const row = data[x]
               chatContainer.innerHTML += '<div class="chat_bubble_container">' + 
                    
                    '<div class="chat_user">' + `<img src="/media/${row.pic_path}" id="chat_tbmnail">` +
                        row.user + 
                    '</div>' + 
                    '<div class="chat_bubbles">' + 
                        row.text + ' ' +
                    '</div>'+ 
                    '<div class="time_cont">' + 
                        '<div class="bubble_timeleft">' + 
                        '</div>' + 
                        '<div class="chat_bubble_time">'+ 
                        '('+dayjs(row.time).fromNow()+')'+ 
                        '</div>' + 
                    '</div>' +
                 '</div>';
        }
       setTimeout(update_messages, 10000);
    }


    catch(error){
        console.log(error);
    }

    
}

document.addEventListener("DOMContentLoaded", function () {
    update_messages();
   const form = document.querySelector('#chat_form');
   const button = document.querySelector('.send_button_chat');
  if (button) {
    button.disabled = true;
    setTimeout(() => {
      button.disabled = false;
    }, 2000);
    form.addEventListener('submit', function () {
    button.disabled = true;
  });
  }
});


</script>

app/dashboard/templates/dashboard/home.html
 {% include 'dashboard/base.html' %}

 {% block content %}
 <div class="left_container">  </div> 

  <div class="center_container">
       {% if user.is_authenticated %}
       <div class="title_container">  <h1 class="home_head">Welcome {{user.first_name}}</h1></div>
       {% endif %}
   
      <div class="text_container">
      <h2 class="home_head">Messages</h2>
      
      <div class="bubble_wrapper"> 
    <div class="bubbles_div">
      {% if reports %}
      {% for report in reports %}
  

      
      <div class="msg_button">
   
      <a href="{% url 'dashboard:reportview' report.id %}"> 
      <div>{{report.user}}: {{report.title}}</div> </a>
      <div class="bubblex_radius">
        <a href="{% url 'dashboard:report_delete' report.id %}" class="delete_bubblex">></a>

      </div>
    
       </div>
      
      {% endfor %}
      {% else %}
      <p class="no_messages"> No messages for the moment</p>
      {% endif %}
       </div>
      </div>
      </div>
   </div>
   <div class="right_container"></div>
 {% endblock %}

app/dashboard/templates/dashboard/homeview.html
 {% include 'dashboard/base.html' %}

 {% block content %}
 <div class="left_container">  </div> 

  <div class="center_container">
    
       {% if user.is_authenticated %}
       <div class="title_container">  <h1 class="home_head">Welcome {{user.first_name}}</h1></div>
       {% endif %}

       <div class="btn-container-msg">
     <div class="messages_send_msg_btn"><a href="{% url 'dashboard:messages_create' %}"><button>Send a message</button></a></div>
      <div class="messages_view_msg_btn"><a href="{% url 'dashboard:inbox' %}"><button>See inbox</button></a></div>
      </div>
      
      <div class="text_container">
        
      <h2 class="home_head">Messages</h2>
      
      <div class="bubble_wrapper"> 
    <div class="bubbles_div">
      {% if reports %}
      {% for report in reports %}
  

      
      <div class="msg_button">
   
      <a href="{% url 'dashboard:reportview' report.id %}" class="bubble_link"> 
      <div>{{report.user}}: {{report.title}}</div> </a>
      <div class="bubblex_radius">
        <a href="{% url 'dashboard:report_delete' report.id %}" class="delete_bubblex">></a>

      </div>
    
       </div>
      
      {% endfor %}
      {% else %}
      <p class="no_messages"> No messages for the moment</p>
      {% endif %}
       </div>
      </div>
      </div>
   </div>
   <div class="right_container"></div>
 {% endblock %}

app/dashboard/templates/dashboard/look_a_report.html
 {% include 'dashboard/base.html' %}
 {% block content %}
 <div class="general_text_container">
  <p class="general_text"> {{ report.content}} </p>
 </div>

 <a href="{% url 'dashboard:reports' %}">
  <button type="button" class="look_btn_back">Back</button>
</a>

{% endblock %}

app/dashboard/templates/dashboard/report.html
{% extends 'dashboard/base.html' %}

{% block content %}

<div class="outer_report">
    
    <div class="left_text">
        <form method="post"> 
        {% csrf_token %}
        <div class="content_title">
                Report :
            </div>
            <div class="content">
            {{form.content}}

            </div>

    </div>
    <div class="right_tasks">
        <div class="tasks_title">
                Join a task :
            </div>
            <div class="tasks">
                {{form.tasks}}
            </div>
            <input type="submit" value="Submit" class="report_submit_btn">
      </form>
    </div>
  
</div>


 <div class="send_msg_back">
   <a href="{% url 'dashboard:home' %}"><button class="del_btn2" type="button">Back</button></a>

 </div>
 {% endblock %}

app/dashboard/templates/dashboard/reports.html
 {% include 'dashboard/base.html' %}

 {% block content %}
 
 <div class="reports_container">
 <h class="title">Reports</h>
 <div class="reports_div">
  <!----  {% load crispy_forms_tags %}-->
<form method="post" class="text_field">
<!--<a href="#" class="add_recipient" onclick="window.open('{% url 'dashboard:add' %}', 'popup', 'width=400,height=300'); return false;">Launch</a>-->
  <a class="add_recipient" href="{% url 'dashboard:add' %}">Add a recipient</a>
  <a class="add_recipient" href="{% url 'dashboard:recipient_delete' %}">Delete recipients</a>


  {% csrf_token %}
 <p class="forms"> {{ form.as_p }}</p>
  <!---- <p class="forms">{{form|crispy}}</p>-->
  <input type="submit" name="send" value="send">
  </form>
 </div>

 <div class="reports_menu">
  <p> Reports History </p>
   {% for report in data %}
   <div class="history">
    <a class ="link_block" href="{% url 'dashboard:report_update' report.id %}" target="_blank">{{report.title}}</a>
  </div>
   {% endfor %}
 </div>
 </div>
 {% endblock %}

app/dashboard/templates/dashboard/reports_confirm_delete.html
 {% include 'dashboard/base.html' %}
{% block content %}
<h1>Delete Report</h1>

<p>Are you sure you want to delete the Report {{ report.name }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Yes, delete.">
</form>
{% endblock %}