app/api/urls.py
from django.urls import path
from . import views
from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView
from django.urls import path, include
from	rest_framework.routers import	DefaultRouter


router = DefaultRouter()
from api.views import MessageViewSet, TaskViewSet,TeamViewSet, UserProfileViewSet
router.register("messages", MessageViewSet)
router.register('tasks', TaskViewSet)
router.register('team', TeamViewSet)


urlpatterns = [

     path("jwt/", TokenObtainPairView.as_view(), name="jwt_obtain_pair"),
     path("jwt/refresh/", TokenRefreshView.as_view(), name="jwt_refresh"),
     path('checkAuth/', views.checkAuth.as_view({'get': 'get'}), name='checkAuth'),
     path("home/", views.Homeview.as_view({'get': 'retrieve'}), name="home"),
     path('team/', views.TeamViewSet.as_view({'get':'list'}), name ='team'),
     path('activate/task/<int:pk>', views.ActivateTask.as_view(),name='activate'),
     path('subtasks/<int:pk>/', views.SubtaskViewSet.as_view({
                                     'post':'create', 'patch':'update'}), name="subtasks"),

     path('subtasks/completed/<int:pk>/', views.SubtaskCompleted, name="subtask_completed"),
     path('upload/', views.ImageUploadView.as_view(), name='upload'),
     path('upload/file/<int:pk>', views.FileUploadView.as_view(), name='uploadFiles'),
     path('chat/', views.ChatViewSet.as_view({'get':'get'}), name='chat'),
     path('chat/submit/', views.SaveMessage.as_view({'post':'post'}), name='savemsg'),
     path('loading/<str:celery_id>/<str:photo>/', views.Ready.as_view({'get': 'get'}), 
          name='ready'),
    # path('messages/unread', views.UnreadMessages.as_view(), name='unread_count'),
     path('profile/', views.UserProfileViewSet.as_view({'get':'retrieve'})),
     path('pushtoken/', views.RegisterPush.as_view(), name='registerpush'),
     path("",	include(router.urls)),

     #path('home')
]

app/dashboard/urls.py
from . import views
from django.urls import path
from .forms import CustomPasswordChangeForm, ProfileUpdateForm


app_name = 'dashboard'
urlpatterns = [
    
    ####### Users , Home#########
    path('options/', views.setOptions, name='options'),
    path('loading/<str:celery_id>/<str:type>/<int:object_id>/<str:arg>', 
         views.LoadingView.as_view(), name= 'loading'),
    path('loading/ready/<str:celery_id>/<str:type>/<int:object_id>/<str:arg>', 
         views.Ready, name='ready'),
         
    path('home/', views.BillboardView.as_view(), name = 'home'),
    path('logout/', views.LogoutView.as_view(), name ='logout'),
    path('report/', views.ReportView.as_view(), name='report'),
    path('role_dispatch/', views.role_dispatch, name='role_dispatch'),
    path('account/<int:pk>', views.AccountView.as_view(), name='user_account'),
    path('account/update/<int:pk>', views.AccountUpdate.as_view(form_class=ProfileUpdateForm),
     name='account_update'),
    path('account/update/password/<int:pk>', views.PasswordChangeView.as_view(
        form_class=CustomPasswordChangeForm), name="password_update"),
 
    ####### Messages ##########
    path('messages/reply/create/<int:recipient_id>', views.ReplyView.as_view(),
          name="message_reply"),
    path('messages/', views.HomeView.as_view(), name='messages'),
    path('messages/create/', views.MessageView.as_view(), name = 'messages_create'),
    path('messages/forward/<int:pk>', views.MessageForward.as_view(), name='message_forward'),
    path('report_detail/<int:id>/', views.MessageDetail.as_view(), name='reportview'),
    path('messages/inbox', views.InboxView.as_view(), name = 'inbox'),
    path('delete_report/<int:pk>', views.MessageDelete.as_view(), name = 'report_delete'),
    path('update_report/<int:pk>', views.MessageUpdate.as_view(), name = 'report_update'),
    ##########TASKS#########
    path('tasks/<int:pk>/activate', views.setActiveTask, name='activate_task'),
    path('tasks/subtask/<int:pk>', views.FetchSubtask, name='fetch_subtask'),
    path('tasks/<int:task>/subtask/<int:pk>', views.SubtaskCompleted, name="subtask_completed"),
    path('tasks/', views.TasksList.as_view(), name = 'tasks_list'),
    path('tasks/<int:pk>/', views.TaskDetail.as_view(), name='task_detail'),
    path('tasks/delete/<int:pk>', views.TaskDelete.as_view(), name = 'task_delete'),
    path('tasks/completed/<int:pk>', views.TaskSubmit.as_view(), name='task_submit'),
    ######### Files #########
    path('pic_picture/<int:pk>', views.stream_file, name='pic_picture'),
    path('pic_picture_completed_task/<int:pk>', views.stream_completed_task_img, 
         name='stream_completed_task_img'),
    path('file/<int:pk>/download', views.GetFile, name="get_file"),
    path('report/<int:pk>/download', views.getReport, name='get_report'),
    path('file/<int:pk>/task/delete/<int:manage>', views.DelFile, name='delete_file'),
    path('resource/<int:pk>', views.getResource, name='get_resource'),
    ####### MANAGE ###########
    path('team/', views.TeamView.as_view(), name = 'team'),
    path('tasks/completed/<int:pk>/', views.TaskCompletedDetail.as_view(), name='task_completed_detail'),
    path('tasks/create/', views.TaskManageCreate.as_view(), name = 'task_manage_create'),
    path('tasks/update/<int:pk>', views.TaskUpdate.as_view(), name = 'task_manage_update'),
    path('tasks/completed/approve/<int:pk>', views.TeamCompletedApprove.as_view(), 
         name = 'task_approve'),
    path('tasks/history/', views.TaskHistoryView.as_view(), name='task_history'),
    path('team/ressources', views.RessourcesView.as_view(), name="ressources"),
    path('team/getSection/<int:chart>', views.getSection, name='get_section'),



    ####### SCHEDULES ########
    path('schedules', views.ScheduleView.as_view(), name = 'schedule_view'),
    path('schedules/<int:pk>', views.ScheduleDetail.as_view(), name = 'schedule_detail'),
    path('schedules/manage', views.ScheduleManage.as_view(), name = 'schedule_manage'),
    path('schedules/update/<int:pk>', views.ScheduleUpdate.as_view(), 
         name = 'schedule_update'),
    path('schedules/user/<int:pk>/availability', views.AvailabilityForm.as_view(), 
         name='availability'),
    path('schedules/user/<int:pk>/request', views.ScheduleChangeRequest.as_view(),
          name='schedule_request'),
 
    #######TEAM ##########
    path('team/update/<int:pk>', views.TeamUpdate.as_view(), name='team_update'),
    path('team/completed/', views.TeamCompletedTask.as_view(), name='team_completed'),
    path('team/user/<int:pk>/stats', views.PerformanceDetail.as_view(), name = 'perf_detail'),
    path('team/<int:pk>/stats', views.PerformanceView.as_view(), name = 'perf_team'),
    path('team/<int:pk>/stats/page/<int:page>', views.PerformanceView.as_view(),
         name='perf_team_detail'),


    ####### Milestones ########
  
    path('history/milestones/team/<int:pk>', views.HistoryView.as_view(), name='history_view'),
    path('team/vs_team', views.TeamVs.as_view(), name="team_vs"),
    
    #######PROJECTS ######
    path('projects', views.ProjectsView.as_view(), name='projects'),
    path('projects/chart/<int:pk>', views.ChartDetail.as_view(), name='chart_detail'),
    path('projects/chart/create', views.ChartCreate.as_view(), name = "chart_create" ),
    path('projects/chart/load/<int:pk>', views.LoadChart, name="load_chart"),
    path('projects/chart/create/add_section/<int:pk>', views.AddSection.as_view(), name="add_section"),
    path('projects/chart/<int:pk>/create/task', views.ChartTaskCreate.as_view(),
          name='create_task_chart'),
    path('projects/chart/<int:chart>/task/<int:pk>/update', views.ChartTaskUpdate.as_view(), name='chart_task_update'),
    path('projects/chart/<int:pk>/update', views.ChartUpdate.as_view(), name='chart_update'),
    path('projects/chart/sections/delete/<int:pk>', views.SectionDelete, name='sections_update'),
    path('projects/chart/<int:pk>/delete', views.ChartDelete.as_view(), name ='chart_delete'),
    path('projects/chart/<int:pk>/reset', views.ChartReset, name='reset_chart'),
    #path('projects/chart/save/<int:pk>', views.SaveChart, name='chart_save'),
    path('projects/chart/<int:task_id>/<int:section_id>/<int:chart_id>/<str:prev>/<str:next>', 
         views.SwapTask, name='swapTask'),
    ######CHAT##########
    path('chat', views.ChatView.as_view(), name='chat_view'),
    path('chat/update/', views.ChatUpdate, name='chat_update'),

] 

app/portal/urls.py
from django.contrib import admin
from django.shortcuts import redirect
from django.urls import path, include, reverse
from dashboard.views import CustomLoginView
from dashboard.views import CustomRegistration
from dashboard.forms import CustomRegistrationForm
from django.conf.urls.static import	static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/' ,include('api.urls')),
    path('accounts/register/',
        CustomRegistration.as_view(form_class=CustomRegistrationForm),
        name='django_registration_register'),

    path("accounts/", include("django_registration.backends.one_step.urls")),
    path("accounts/", include("django.contrib.auth.urls")),
    path('dashboard/', include('dashboard.urls', namespace='dashboard')),
    path('', CustomLoginView.as_view(template_name='dashboard/login.html')),
    path('__debug__/', include('debug_toolbar.urls')),

]
urlpatterns+= static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns+= static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

app/dashboard/templates/dashboard/Messages/inbox.html
 {% include 'dashboard/base.html' %}

 {% block content %}


  <div class="center_container_inbox">
    
       {% if user.is_authenticated %}
       <div class="title_container_inbox">  <h1 class="home_head">Inbox</h1></div>
       {% endif %}


            <div class="btn-container-msg">
       <div class="messages_send_msg_btn"><a href="{% url 'dashboard:messages_create' %}"><button class="send_a_msg_btn">Send a message</button></a></div>
       <form id="myForm" method="post">
               {% csrf_token %}
        <!-- Hidden inputs will be added here -->
        <button type="submit" class="delete_selected_messages">Delete selected</button>
      </form>

      </div>


     



      <div class="text_container_inbox">
        
<div class="form_seach_container">  

        <form class="search_bar_inbox">
       <input type="text" placeholder="Search.." name="search"
         class="search_bar_input">
     <button class="search_inbox_btn" type="submit">Search / Clear</button>
        </form>
</div>


     {% if not messages %}
     <p class="no_messages"> No messages for the moment</p>
     {% endif %}
      
      <div class="bubble_wrapper_inbox"> 
    <div class="bubbles_div_inbox">
      {% if messages %}
      {% for message in messages %}
  

      
      <div class="msg_button_inbox">
    
    <div class="text_div_bubble_inbox">
        
      <a href="{% url 'dashboard:reportview' message.id %}" class="bubble_link_inbox"> 
      {% if not message.forwarded %}
      <div class="msg_content_inbox"><strong>{{message.user}}: </strong>{{message.title}} </div> </a>
       </div>
       {% else %}
        <div class="msg_content_inbox"><strong>{{message.forwarded_by}}: </strong>
          {{message.title}}<strong><em> (forwarded from {{message.user}})  </em></strong> </div> </a>
       </div>
       {% endif %}
      <p class="msg_date">{{message.timestamp}}</p>
      <a href="{% url 'dashboard:message_forward' message.id %}" class="delete_bubblex_inbox">
         <div class="bubblex_radius_inbox"> > </div> </a>
     

   
            <div class="tickbox" onclick="fillbox('{{message.id}}');selectBox(this)" id="{{message.id}}"></div>
       </div>
      
      {% endfor %}
   
      
      {% endif %}
       </div>
      </div>
      </div>
   </div>



   <div class="send_msg_back">
   <a href="{% url 'dashboard:messages' %}"><button class="del_btn2" type="button">Back</button></a>

 </div>
 {% endblock %}



<script>


function fillbox(n) {
 
  const box = document.getElementById(n);
  const selected = box.getAttribute('is_selected') === 'true';

  if (selected){
    box.style.backgroundColor='transparent';
    box.setAttribute('is_selected', 'false');
    
  }

  else {
   box.style.backgroundColor = '#B5D4F4'
   box.setAttribute('is_selected', 'true');
  }
}


function selectBox(element) {
  const form = document.getElementById('myForm');
  const boxId = element.id;

  // Toggle selection style
  element.classList.toggle('selected');

  // Check if already selected
  const existingInput = document.getElementById('input_' + boxId);

  if (element.classList.contains('selected')) {
    // Add hidden input to form
    if (!existingInput) {
      const input = document.createElement('input');
      input.type = 'hidden';
      input.name = 'selected_boxes';  // Pass as array
      input.value = boxId;
      input.id = 'input_' + boxId;
      form.appendChild(input);
    }
  } else {
    // Remove hidden input if deselected
    if (existingInput) {
      form.removeChild(existingInput);
    }
  }
}

</script>

app/dashboard/templates/dashboard/Messages/message_detail.html
 {% include 'dashboard/base.html' %}
 {% load user_data %}
 {% block content %}
 
 {% load static %}
 <div class="top_visual_frame_detail"></div>

 {% for document in documents %}
 

    <img src="{% url 'dashboard:pic_picture' document.id %}" 
    id="large{{document.id}}" onclick="hideOverlay('{{document.id}}');" class="big_img">

{% endfor %}


 <div class="visual_frame_msg_detail"> 


{% if previous_index %}
<a href="{% url 'dashboard:reportview' previous_index %}">
<button class="msg_detail_prev_btn"><</button>
</a>
{% endif %}


{% if next_index %}
<a href="{% url 'dashboard:reportview' next_index %}">
<button class="msg_detail_next_btn">></button>
</a>
{% endif %}


 <div class="general_text_container_msg_detail">
        <div class="from_who_title_msg_detail">
            
            <div class="from_who_msg_detail_limt"><strong>From {{report.user.username}} :  </div>
            </strong> 
            <div> {{report.timestamp}}</div>

            </div> 
  <div class="general_text_detail_msg">

{{ report.content}} 

 

  </div>




 </div>




<div class="data_container__view_msg">   


</div>



<div class="msg_detail_infopanel">
        <div class="files_div_messages_detail"> 
        <div class="attachments_title_msg_detail">
            Attachments
        </div>
        {% for document in documents %}
            {% if document.id|slicer == "image" %}
            <div class="image_div_msg_detail">
            <img src="{% url 'dashboard:pic_picture' document.id %}" 
            id="thumbnail{{document.id}}" 
            onclick="showOverlay('{{document.id}}');" style="width: 100%;
            cursor: pointer;
            ">
            </div>
            {% else %}
            <a href="{% url 'dashboard:pic_picture' document.id %}">
            <div class="file_div_msg_detail"> 
                
                <div class="file_name_div"> {{document.file_name}}  </div> 

                
                 <div class="image_icon_div_msg_detail">
                   
                <img src="{% static 'file_icon3.png' %}"style="z-index: 1;width: 100%;">
                </div>
              
           </div>
            </a>
            {% endif %}
        {% endfor %}
        </div>


</div>


</div>



 <div class="bot_visual_frame_detail"></div>

<div id="dark_screen_image_overlay" style="
width: 100vw;
height: 100vh;
background-color: rgba(0, 0, 0, 0.57);
z-index: 100;
position: absolute;
left: 50%;
top: 50%;
transform: translate(-50%, -50%);
display: none;
">
</div>

<script>
function showOverlay(id) {
    document.getElementById('large'+ id).style.display = 'block';
    document.getElementById('thumbnail' + id).style.display = 'none';
    document.getElementById('dark_screen_image_overlay').style.display ='block'
}

function hideOverlay(id) {
    document.getElementById('large' + id).style.display = 'none';
    document.getElementById('thumbnail' + id ).style.display = 'block';
    document.getElementById('dark_screen_image_overlay').style.display ='none'
}
</script>


<div class="send_msg_back_flex">
 <a href="{% url 'dashboard:inbox' %}">
  <button type="button" class="del_btn2">Back</button>
</a>
<a href="{% url 'dashboard:message_reply' report.user.userprofile.id %}"> 
<button type="button" class="del_btn2">Reply</button>
</a>



</div>



{% endblock %}

app/dashboard/templates/dashboard/Messages/message_forward.html
 {% include 'dashboard/base.html' %}

 {% block content %}
<div class="visual_frame_forward">
  <div class="forward_title"> Forward a message</div>
  <form method="post" class="message_forward_form_textarea">
      {% csrf_token %}
 
    {{ form.recipient }}
  <input type="submit" name="send" value="Forward" class="button_forward"> 
 </form>

</div>
  <div class="send_msg_back">
   <a href="{% url 'dashboard:inbox' %}"><button class="del_btn2" type="button">Back</button></a>

 </div>
  {% endblock %}

app/dashboard/templates/dashboard/Messages/messages.html
 {% include 'dashboard/base.html' %}

 {% block content %}
 
 <div class="reports_container">
  
 <h class="title">Reports</h>
 <div class="reports_div">


<div class="reports_div_top_section"> 
<form method="post" enctype="multipart/form-data">
 {% csrf_token %}

<div class="add_rec_title_div"> 
  
 {{form.title.label_tag}}
 <div class="title_bar_send_msg">{{form.title}} </div>
 <div class="link_divs_send_msg"> 
  <a class="add_recipient" href="{% url 'dashboard:add' %}">Add a recipient |</a>
   <a class="add_recipient" href="{% url 'dashboard:recipient_delete' %}">Delete recipients</a>
   </div>
</div>
   </div>

<div class="send_msg_textarea">  

   <div  class="bottom_left_send_msg"> 
        <div>{{form.content.label_tag}}    </div>
        {{form.content}}

    <div class="bottom_inputs_send_msg">
    <div class="bottom_send_msg"> <div class="filefield_send_msg">{{form.picture}} </div>
  <input class="send_msg_btn_create" type="submit" name="send" value="Send"></div>
 </div>
  </div>
  <div class="bottom_right_send_msg">
  <div>{{form.recipient.label_tag}} </div>
 {{ form.recipient }} 

  </div>
  </div>


  </form>
 </div>

 <div class="reports_menu">
  <div class="history_title"> Reports History </div>
   {% for report in data %}
   <div class="history">
    <a class ="link_block" href="{% url 'dashboard:report_update' report.id %}" target="_blank">{{report.title}}</a>
  </div>
   {% endfor %}
  
 </div>
 </div>
 <div class="send_msg_back">
   <a href="{% url 'dashboard:messages' %}"><button class="del_btn2" type="button">Back</button></a>

 </div>

 {% endblock %}

app/dashboard/templates/dashboard/Messages/messages_confirm_delete.html
 {% include 'dashboard/base.html' %}
{% block content %}
<h1>Delete Report</h1>

<p>Are you sure you want to delete the Report {{ report.name }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Yes, delete.">
</form>
{% endblock %}

app/dashboard/templates/dashboard/Messages/messages_send.html
 {% include 'dashboard/base.html' %}

 {% block content %}
 <div class="top_visual_frame_task_list"></div>
 <div class="reports_container">
  
 <div class="title">Reports</div>
 <div class="reports_div">


<div class="reports_div_top_section"> 
<form method="post" enctype="multipart/form-data">
 {% csrf_token %}

<div class="add_rec_title_div"> 
  
 {{form.title.label_tag}}
 <div class="title_bar_send_msg">{{form.title}} </div>
 <div class="link_divs_send_msg"> 
  <a class="add_recipient" onclick="document.getElementById('shade_background_modal_add').style.display = 'flex'">Add a recipient |</a>
   <a class="add_recipient" onclick="document.getElementById('shade_background_modal_del').style.display = 'flex'"> | Delete recipients</a>
   </div>
</div>
   </div>

<div class="send_msg_textarea">  

   <div  class="bottom_left_send_msg"> 
        <div>{{form.content.label_tag}}    </div>
        {{form.content}}

    <div class="bottom_inputs_send_msg">
    <div class="bottom_send_msg"> <div class="filefield_send_msg">
      {{file_form.file_field}} 
    </div>
  <input class="send_msg_btn_create" type="submit" name="send" value="Send"></div>
  
 </div>
   {% if file_form.errors %}
     <div class="send_messages_error"> {{file_form.file_field.errors}}  </div>
      {% endif %} 
  </div>
  <div class="bottom_right_send_msg">
  <div>{{form.recipient.label_tag}} </div> 
  {{ form.recipient }}

  </div>
  </div>


  </form>
 </div>

 <div class="reports_menu">
  <div class="history_title"> Reports History </div>
   {% for report in data %}
   <div class="history">
    <a class ="link_block" href="{% url 'dashboard:report_update' report.id %}">{{report.title}}</a>
  </div>
   {% endfor %}
  
 </div>
 </div>
 <div class="send_msg_back">
   <a href="{% url 'dashboard:messages' %}"><button class="del_btn2" type="button">Back</button></a>

 </div>
 <div class="bot_visual_frame_send_msg"></div>



 <!-------------------------------ADD & DELETE MODALS----------------------------------->


<!------------------ADD FORM----------------------->
 <div id="shade_background_modal_add" style="
 width: 100vw; 
 height: 100vh;
 background-color: rgba(0, 0, 0, 0.714);
 display: none;
 position: absolute;
 left: 50%;
 top: 50%;
 transform: translate(-50%,-50%);
 
 ">
 <div class="add_form_container">


 



 
    <h1 class="title_add"> Add contacts</h1>
 <form method="post" class="add_contact_form"> 
    
 
      <button type="submit" class="left_add_btn" name="add">Add</button> 
    



   
     
         <button onclick="document.getElementById('shade_background_modal_add').style.display='none'"
          type="button" class="right_add_btn">Close</button>
    
      

   
      
      {% csrf_token %}
      {{form_add.recipients}}
 
  
  </form>

 </div>

 </div>


<!---------------------DEL FORM ------------------------>

 <div id="shade_background_modal_del" style="
 width: 100vw; 
 height: 100vh;
 background-color: rgba(0, 0, 0, 0.714);
 display: none;
 position: absolute;
 left: 50%;
 top: 50%;
 transform: translate(-50%,-50%);
 
 ">
 
 <div class="add_form_container">


     <h1 class="title_add"> Delete contacts</h1>



 
 <form method="post" class="add_contact_form"> 
 
  
      <button type="submit"  class="left_add_btn" name="delete">Delete</button> 
    



       <button onclick="document.getElementById('shade_background_modal_del').style.display='none'"
          type="button" class="right_add_btn">Close</button>
      

   
      
      {% csrf_token %}
      {{form_del.recipients}}
 
  
  
  </form>


 </div>


 </div>
 {% endblock %}

app/dashboard/templates/dashboard/Messages/messages_update.html
 {% include 'dashboard/base.html' %}

 {% block content %}
<div class="visual_frame_update">

<div class="top_send_msg_update">  
  <form method="post" enctype="multipart/form-data">
      {% csrf_token %}
     <div class="title_container_send_msg_update">
      {{form.title.label_tag}}
      {{form.title}}   
               </div>   
 </div>

<div class="bottom_send_msg_update">
 
 <div class="send_update_text_area"> 
       <div class="send_msg_update_content_tag">{{form.content.label_tag}} </div> 
       {{form.content}} </div>

  <div class="send_update_recipients">  
   {{form.recipient.label_tag}}   
 <div class="send_msg_update_recipient"> {{ form.recipient }}</div>     </div> 
</div>
<div class="msg_update_bottom_cont_flex">

   
     <div>{{file_form.file_field}}</div>
   
     <input type="submit" name="send" value="Update" class="send_msg_update_submit">
     
      {% if file_form.errors %}
    <div style="color: rgb(19, 19, 19); font-weight: bold;
    font-size: smaller;"> {{file_form.file_field.errors}}
    </div> 
      {% endif %} 


</div>
  
 </form>

</div>




  <div class="send_msg_back">
   <a href="{% url 'dashboard:messages_create' %}">
    <button class="del_btn2" type="button">Back</button></a>
 </div>
  {% endblock %}

app/dashboard/templates/dashboard/Messages/messages_view.html
 {% extends 'dashboard/base.html' %}
 {% load cache %}
 {% block content %}
  

  <div class="center_container">
     

       {% if user.is_authenticated %}
       <div class="title_container">  <h1 class="home_head">Welcome {{user.first_name}}</h1></div>
       {% endif %}

        {% cache 3600 welcome_section %}
       <div class="btn-container-msg">
        <div class="messages_send_msg_btn">
            <a href="{% url 'dashboard:messages_create' %}">
                <button class="send_a_msg_btn">
                  Send a message
                </button>
              </a>
          </div>
      <div class="messages_view_msg_btn"><a href="{% url 'dashboard:inbox' %}"><button class="view_a_msg_btn">See inbox</button></a></div>
      </div>
       {% endcache %}
      <div class="text_container">
   
      <h2 class="home_head">Messages</h2>
     
      <div class="bubble_wrapper"> 
    <div class="bubbles_div">
      {% if reports %}
      {% for report in reports %}
  

      
      <div class="msg_button">
   
      <a href="{% url 'dashboard:reportview' report.id %}" class="bubble_link"> 
      <div>{{report.user}}: {{report.title}}</div> </a>
      <div class="bubblex_radius">
        <a href="{% url 'dashboard:message_forward' report.id %}" class="delete_bubblex">></a>

      </div>
    
       </div>
      
      {% endfor %}
      {% else %}
      <p class="no_messages"> No messages for the moment</p>
      {% endif %}
       </div>
      </div>
      </div>
   </div>
    {% cache 3600 backbutton %}
      <div class="send_msg_back">
        
      <a href="{% url 'dashboard:home' %}"><button class="del_btn2" type="button">
        Back
      </button>
      </a>

     </div>
    {% endcache %}
 {% endblock %}

app/dashboard/templates/dashboard/Messages/reply_view.html
 {% include 'dashboard/base.html' %}

 {% block content %}
 <div class="top_visual_frame_task_list"></div>
 <div class="reports_container_reply">
  
 
 <div class="reports_div_reply">

<div class="reply_msg_title_recipient">Replying to {{recipient.user.username}}</div> 
<div class="reports_div_top_section_reply"> 
    
<form method="post" enctype="multipart/form-data">
 {% csrf_token %}

<div class="add_rec_title_div_reply"> 
  
 {{form.title.label_tag}}

 <div class="title_bar_send_msg_reply">{{form.title}} </div>
 <div class="link_divs_send_msg"> 

   </div>
</div>
   </div>

<div class="send_msg_textarea">  

   <div  class="bottom_left_send_msg_update"> 
        <div>{{form.content.label_tag}}    </div>
        {{form.content}}

    <div class="bottom_inputs_send_msg">
    <div class="bottom_send_msg"> <div class="filefield_send_msg">
      {{file_form.file_field}}
    </div>
  <input class="send_msg_btn_create_reply" type="submit" name="send" value="Send"></div>
  
 </div>
   {% if file_form.errors %}
     <div class="send_messages_error" style="color: rgb(53, 53, 53); margin-left: 1%;
     font-weight: bold;"> 
      {{file_form.file_field.errors}}  </div>
      {% endif %} 
  </div>
  <div class="bottom_right_send_msg">



  </div>
  </div>


  </form>
 </div>


 </div>
 <div class="send_msg_back">
   <a href="{% url 'dashboard:messages' %}"><button class="del_btn2" type="button">Back</button></a>

 </div>
 <div class="bot_visual_frame_send_msg"></div>






 {% endblock %}