app/api/urls.py
from django.urls import path
from . import views
from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView
from django.urls import path, include
from	rest_framework.routers import	DefaultRouter


router = DefaultRouter()
from api.views import MessageViewSet, TaskViewSet,TeamViewSet, UserProfileViewSet
router.register("messages", MessageViewSet)
router.register('tasks', TaskViewSet)
router.register('team', TeamViewSet)


urlpatterns = [

     path("jwt/", TokenObtainPairView.as_view(), name="jwt_obtain_pair"),
     path("jwt/refresh/", TokenRefreshView.as_view(), name="jwt_refresh"),
     path('checkAuth/', views.checkAuth.as_view({'get': 'get'}), name='checkAuth'),
     path("home/", views.Homeview.as_view({'get': 'retrieve'}), name="home"),
     path('team/', views.TeamViewSet.as_view({'get':'list'}), name ='team'),
     path('activate/task/<int:pk>', views.ActivateTask.as_view(),name='activate'),
     path('subtasks/<int:pk>/', views.SubtaskViewSet.as_view({
                                     'post':'create', 'patch':'update'}), name="subtasks"),

     path('subtasks/completed/<int:pk>/', views.SubtaskCompleted, name="subtask_completed"),
     path('upload/', views.ImageUploadView.as_view(), name='upload'),
     path('upload/file/<int:pk>', views.FileUploadView.as_view(), name='uploadFiles'),
     path('chat/', views.ChatViewSet.as_view({'get':'get'}), name='chat'),
     path('chat/submit/', views.SaveMessage.as_view({'post':'post'}), name='savemsg'),
     path('loading/<str:celery_id>/<str:photo>/', views.Ready.as_view({'get': 'get'}), 
          name='ready'),
    # path('messages/unread', views.UnreadMessages.as_view(), name='unread_count'),
     path('profile/', views.UserProfileViewSet.as_view({'get':'retrieve'})),
     path('pushtoken/', views.RegisterPush.as_view(), name='registerpush'),
     path("",	include(router.urls)),

     #path('home')
]

app/dashboard/urls.py
from . import views
from django.urls import path
from .forms import CustomPasswordChangeForm, ProfileUpdateForm


app_name = 'dashboard'
urlpatterns = [
    
    ####### Users , Home#########
    path('options/', views.setOptions, name='options'),
    path('loading/<str:celery_id>/<str:type>/<int:object_id>/<str:arg>', 
         views.LoadingView.as_view(), name= 'loading'),
    path('loading/ready/<str:celery_id>/<str:type>/<int:object_id>/<str:arg>', 
         views.Ready, name='ready'),
         
    path('home/', views.BillboardView.as_view(), name = 'home'),
    path('logout/', views.LogoutView.as_view(), name ='logout'),
    path('report/', views.ReportView.as_view(), name='report'),
    path('role_dispatch/', views.role_dispatch, name='role_dispatch'),
    path('account/<int:pk>', views.AccountView.as_view(), name='user_account'),
    path('account/update/<int:pk>', views.AccountUpdate.as_view(form_class=ProfileUpdateForm),
     name='account_update'),
    path('account/update/password/<int:pk>', views.PasswordChangeView.as_view(
        form_class=CustomPasswordChangeForm), name="password_update"),
 
    ####### Messages ##########
    path('messages/reply/create/<int:recipient_id>', views.ReplyView.as_view(),
          name="message_reply"),
    path('messages/', views.HomeView.as_view(), name='messages'),
    path('messages/create/', views.MessageView.as_view(), name = 'messages_create'),
    path('messages/forward/<int:pk>', views.MessageForward.as_view(), name='message_forward'),
    path('report_detail/<int:id>/', views.MessageDetail.as_view(), name='reportview'),
    path('messages/inbox', views.InboxView.as_view(), name = 'inbox'),
    path('delete_report/<int:pk>', views.MessageDelete.as_view(), name = 'report_delete'),
    path('update_report/<int:pk>', views.MessageUpdate.as_view(), name = 'report_update'),
    ##########TASKS#########
    path('tasks/<int:pk>/activate', views.setActiveTask, name='activate_task'),
    path('tasks/subtask/<int:pk>', views.FetchSubtask, name='fetch_subtask'),
    path('tasks/<int:task>/subtask/<int:pk>', views.SubtaskCompleted, name="subtask_completed"),
    path('tasks/', views.TasksList.as_view(), name = 'tasks_list'),
    path('tasks/<int:pk>/', views.TaskDetail.as_view(), name='task_detail'),
    path('tasks/delete/<int:pk>', views.TaskDelete.as_view(), name = 'task_delete'),
    path('tasks/completed/<int:pk>', views.TaskSubmit.as_view(), name='task_submit'),
    ######### Files #########
    path('pic_picture/<int:pk>', views.stream_file, name='pic_picture'),
    path('pic_picture_completed_task/<int:pk>', views.stream_completed_task_img, 
         name='stream_completed_task_img'),
    path('file/<int:pk>/download', views.GetFile, name="get_file"),
    path('report/<int:pk>/download', views.getReport, name='get_report'),
    path('file/<int:pk>/task/delete/<int:manage>', views.DelFile, name='delete_file'),
    path('resource/<int:pk>', views.getResource, name='get_resource'),
    ####### MANAGE ###########
    path('team/', views.TeamView.as_view(), name = 'team'),
    path('tasks/completed/<int:pk>/', views.TaskCompletedDetail.as_view(), name='task_completed_detail'),
    path('tasks/create/', views.TaskManageCreate.as_view(), name = 'task_manage_create'),
    path('tasks/update/<int:pk>', views.TaskUpdate.as_view(), name = 'task_manage_update'),
    path('tasks/completed/approve/<int:pk>', views.TeamCompletedApprove.as_view(), 
         name = 'task_approve'),
    path('tasks/history/', views.TaskHistoryView.as_view(), name='task_history'),
    path('team/ressources', views.RessourcesView.as_view(), name="ressources"),
    path('team/getSection/<int:chart>', views.getSection, name='get_section'),



    ####### SCHEDULES ########
    path('schedules', views.ScheduleView.as_view(), name = 'schedule_view'),
    path('schedules/<int:pk>', views.ScheduleDetail.as_view(), name = 'schedule_detail'),
    path('schedules/manage', views.ScheduleManage.as_view(), name = 'schedule_manage'),
    path('schedules/update/<int:pk>', views.ScheduleUpdate.as_view(), 
         name = 'schedule_update'),
    path('schedules/user/<int:pk>/availability', views.AvailabilityForm.as_view(), 
         name='availability'),
    path('schedules/user/<int:pk>/request', views.ScheduleChangeRequest.as_view(),
          name='schedule_request'),
 
    #######TEAM ##########
    path('team/update/<int:pk>', views.TeamUpdate.as_view(), name='team_update'),
    path('team/completed/', views.TeamCompletedTask.as_view(), name='team_completed'),
    path('team/user/<int:pk>/stats', views.PerformanceDetail.as_view(), name = 'perf_detail'),
    path('team/<int:pk>/stats', views.PerformanceView.as_view(), name = 'perf_team'),
    path('team/<int:pk>/stats/page/<int:page>', views.PerformanceView.as_view(),
         name='perf_team_detail'),


    ####### Milestones ########
  
    path('history/milestones/team/<int:pk>', views.HistoryView.as_view(), name='history_view'),
    path('team/vs_team', views.TeamVs.as_view(), name="team_vs"),
    
    #######PROJECTS ######
    path('projects', views.ProjectsView.as_view(), name='projects'),
    path('projects/chart/<int:pk>', views.ChartDetail.as_view(), name='chart_detail'),
    path('projects/chart/create', views.ChartCreate.as_view(), name = "chart_create" ),
    path('projects/chart/load/<int:pk>', views.LoadChart, name="load_chart"),
    path('projects/chart/create/add_section/<int:pk>', views.AddSection.as_view(), name="add_section"),
    path('projects/chart/<int:pk>/create/task', views.ChartTaskCreate.as_view(),
          name='create_task_chart'),
    path('projects/chart/<int:chart>/task/<int:pk>/update', views.ChartTaskUpdate.as_view(), name='chart_task_update'),
    path('projects/chart/<int:pk>/update', views.ChartUpdate.as_view(), name='chart_update'),
    path('projects/chart/sections/delete/<int:pk>', views.SectionDelete, name='sections_update'),
    path('projects/chart/<int:pk>/delete', views.ChartDelete.as_view(), name ='chart_delete'),
    path('projects/chart/<int:pk>/reset', views.ChartReset, name='reset_chart'),
    #path('projects/chart/save/<int:pk>', views.SaveChart, name='chart_save'),
    path('projects/chart/<int:task_id>/<int:section_id>/<int:chart_id>/<str:prev>/<str:next>', 
         views.SwapTask, name='swapTask'),
    ######CHAT##########
    path('chat', views.ChatView.as_view(), name='chat_view'),
    path('chat/update/', views.ChatUpdate, name='chat_update'),

] 

app/portal/urls.py
from django.contrib import admin
from django.shortcuts import redirect
from django.urls import path, include, reverse
from dashboard.views import CustomLoginView
from dashboard.views import CustomRegistration
from dashboard.forms import CustomRegistrationForm
from django.conf.urls.static import	static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/' ,include('api.urls')),
    path('accounts/register/',
        CustomRegistration.as_view(form_class=CustomRegistrationForm),
        name='django_registration_register'),

    path("accounts/", include("django_registration.backends.one_step.urls")),
    path("accounts/", include("django.contrib.auth.urls")),
    path('dashboard/', include('dashboard.urls', namespace='dashboard')),
    path('', CustomLoginView.as_view(template_name='dashboard/login.html')),
    path('__debug__/', include('debug_toolbar.urls')),

]
urlpatterns+= static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns+= static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

app/dashboard/templates/dashboard/Management/perf_view.html
 {% include 'dashboard/base.html' %}
{% block content %}


<div class="extreme_outer_div_graph">

<div class="left_graph_panel">
    <div class="graph_btns_frame">
               

    {% for n in ranges %}
        <div class="graph_left_btn_div">
        <a href="{% url 'dashboard:perf_team_detail' user.userprofile.team.id n %}">
            <button class="graph_side_btn"> Metrics {{forloop.counter}}</button>
            </a>
        </div>
   
    {% endfor %}
 </div>
 <div class="graph_stats_left_frame">
    <div class="graph_stats_title1">Tasks</div>
    <div class="graph_stats_divs">Mean time: {{task_mean_time}} h</div>
    <div class="graph_stats_divs">Late ratio: {{late_ratio}} %</div>
    <div class="graph_stats_divs">Denied ratio: {{denied_ratio}} % </div>
    <div class="graph_stats_divs">Urgent ratio: {{urgent_ratio}} %</div>

 </div>
</div>

<div class="graph_container1">
    
<h1 class="title_graphs"> {{date_string }}</h1>

    <div class="graph1">
        {{plot1|safe }}
          
    </div>
  
</div>
<div class="graph_container2">
    


    <div class="graph2">
        {{ plot2|safe }}
          
           
    </div>
     
   
</div>

</div>

{% endblock %}

app/dashboard/templates/dashboard/Management/task_detail.html
 {% include 'dashboard/base.html' %}
 
 {% block content %}
   <div class="top_visual_frame_task_list_management"></div>
<div class="extreme_outer_div_task_manage_detail">  

   <div class="task_detail_left_panel_manage">
           

          <div class ="title_task_view">{{task.name}}</div>
          <div class="flex_container_task_view">Due date : {{task.due_date}} </div>
          <div class="flex_container_task_view">Took : {{task.completion_time}} h</div>
          <a onclick="document.getElementById('popup').style.display='flex'">
                <button class="task_detail_completed_link">Description  
              </button>
           </a>
            <a href="{% url 'dashboard:task_manage_update' task.id %}">
                <button class="task_detail_completed_link">More details  
              </button>
           </a>
                
          <div class="title_data">Team</div>
    

          <div class="left_bar_team_members_container">
              {% for user in task.users.all %}
              <div class="task_completed">{{user.user.username}}</div>
              {% endfor %}


            
              
          </div>
    
{% if task.content_type %}
   {% load static %}
<div class="images_title"> Images</div>
      <div class="image_container_task_review_detail">
        <img id="thumbnail_img_icon" style=" width: 28%; position: relative;" 
         src="{% static 'img_icon2.png' %}"
         onclick="showOverlay();">
          </div>
{% endif %}

     </div>

          <div class="text_frames_container_management">  
            

              <div class="title_completion_note"> 
          
                   Completion note 
               
              </div>
           
              <div class="second_text_container_management">
                  <p class="general_text_management2">  {{task.completion_note}}</p>
             </div>

          </div>    



 <div class="task_detail_right_panel">


    <div class="task_completed_btn_container">
         <a href="{% url 'dashboard:task_approve' task.id %}">
         <button type="button" class="task_detail_completed_btn">Approve</button>
        </a>
    </div>
 

    <div class="task_completed_deny_container">
           <form class="form_deny_text" method="post">
           {% csrf_token %}
           <button class="btn_deny" type="submit">Deny</button>
   </div> 

    <div class="task_completed_deny_container2"> 
           {{form.deny_reason.label_tag}}
           {{form.deny_reason}}
 
           </form>
    </div>    

</div>

 </div>
        <div class="send_msg_back">
          <a href="{% url 'dashboard:team_completed' %}"><button class="del_btn2" type="button">Back</button></a>

        </div>
   </div>

  {% if task.content_type %}
     <div id="overlay" class="overlay" style="display: none; text-align: center;"
     onclick="hideOverlay();">
    <img style="width:85%;margin-top: 5px; border:3px solid black;" 
         src="{% url 'dashboard:stream_completed_task_img' task.id %}">
  </div>
  {% endif %}
<div class="bot_visual_frame_task_list"></div>



<!--------------------------------------MODAL------------------------------------------->

                <div id="popup" style="
                  display: none;
                  position: absolute;
                  left: 50%;
                  top:50%;
                  transform: translate(-50%,-50%);
                  width: 100vw; height: 100vh;
                  background: rgba(0,0,0,0.5);
                  justify-content: center;
                  align-items: center;
                  z-index: 100;
                ">
                  <div style="
                     background-color: rgb(156, 129, 105);
                    width: 60vw; height: 81vh;
                    padding: 20px;
                    border-radius: 8px;
                    margin-top: 1%;
                    display: flex;
                    flex-direction: column;
                  ">
                  <div class="task_description_title_modal_manage">Description</div>
                  <p class="task_description_text_modal_manage">{{task.description}}</p>
             
                  <button class="task_modal_manage_btn" onclick="document.getElementById('popup').style.display='none'">Close</button>
               
            </div>





<script>


function showOverlay() {
    document.getElementById('overlay').style.display = 'block';
    document.getElementById('thumbnail').style.display = 'none';
}

function hideOverlay() {
    document.getElementById('overlay').style.display = 'none';
    document.getElementById('thumbnail').style.display = 'inline';
}
</script>



{% endblock %}

app/dashboard/templates/dashboard/Management/task_history.html
{% extends 'dashboard/base.html' %}
{% load user_data %}
{% block content %}
<div class="big_wrapper">


<div class="outer_history">
  
 
        <div class="title_div">
         Tasks history
        </div>
        <div class="grid_titles">
                <div class="name_title">
                    Name
                </div>
                <div class="submitted_at_title">
                    Submitted at
                </div>
                 
            </div>
        <div class="main_content">
            
             {% for task in tasks %}
             
             <div class="task_div">

                <div class="task_title"  id="people{{task.id}}"
            data-member="{{task|get_team}}">
                     {{task.name}}
                </div>
                <div class="task_submitted {% if task.submitted_at > task.due_date %} 
                task_late {% endif %}">
                  {{task.submitted_at}}
                </div>
                
             </div>
             {% endfor %}

        </div>
</div>
<div class="filters">
    <div class="filter_title">
        Filters
    </div>


    <div class="reset_div"> 
      <form method="GET">
        
       <input type="submit" name="late" class="late_input" value="Late tasks">
    </form>
      <a href="{% url 'dashboard:task_history' %}">
        <input type="button" value="Reset filters">
      </a>
    </div>


      <form method="GET" class="date_filters">
        <div>
           From: {{form.from_field}}
        </div>
          <div class="to_input">
         To: {{form.to}}
          </div>
          <div>
            
          </div>
               <input type="submit" value="Filter" class="date_submit" name="date_filter">
             
     </form>
    

</div>
</div>
   <div id="info_modal_team" style="z-index: 1000;">
         <div class="team_list_title">
             Team

         </div>
         <div id="text_team"></div>
          
       </div>


 </div>
        <div class="send_msg_back">
          <a href="{% url 'dashboard:team' %}"><button class="del_btn2" type="button">Back</button></a>

        </div>
   </div>
<script>
    document.addEventListener('DOMContentLoaded', () => {
 
    setTeamBubble();
});

</script>
{% endblock %}

app/dashboard/templates/dashboard/Management/team_view.html
 {% extends 'dashboard/base.html' %}
 {% load static user_data %}
 {% block extra_css %}
 <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
<script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
<style>

</style>
 {% endblock %}
 {% block content %}



 <h1 class="team_title">
   {% if user.userprofile.team.team_lead == user.userprofile %}
   {{user.userprofile.team.name}} management
   {% else %}
    {{user.userprofile.team.name}}
    {% endif %}
  </h1> 


<div class="border_container"> 
    {% if user.userprofile.team.team_lead == user.userprofile %}
    <div class="top_buttons_container"> 
      <div class="team_second_title">
         {% if user.userprofile.team.team_lead == user.userprofile %}
            <button onclick="setVisible(this, 'team_tasks', 'team_all_task_list', 'team_status');
            document.getElementById('team_buttons').style.display='block'" 
            id="toggle_manage" class="management_tog_btn">
               Tasks
            </button>
             <button onclick="setVisible(this, 'team_status', 'team_all_task_list', 'team_tasks', 'team_buttons', 'grid')" 
            id="toggle_manage" class="management_tog_btn">
               Statuses
            </button>
            <button onclick="setVisible(this, 'team_all_task_list', 'team_tasks', 'team_status');
            document.getElementById('team_buttons').style.display='block'" 
            id="toggle_manage" class="management_tog_btn">
               Task list
            </button>
            {% endif %}
     </div>
     <div class="nav_cont">
         
               <button class="scroll_not_manage" onclick="scrollToBot('team_tasks', 'team_all_task_list')"> ▼
               </button>
               <button class="scroll_not_manage" onclick="scrollRight('team_tasks')">▶</button>
               <button class="scroll_not_manage" onclick="reset('team_tasks', 'team_all_task_list')">Reset</button>
                   <div class="filter_form">
           
           
            
            
            </div>

     </div>

      <div class="filter_cont">
              <form method="get">
              {{form.role}}
            </form>
              <div>
               <a href="{% url 'dashboard:team' %}" class="filter_clear">Clear</a>
             </div>
          
      </div>
     <a href="{% url 'dashboard:task_history' %}" class="task_history_div">
     
        <img src="{% static 'arrow_icon2.png' %}" style="height: 70%;">
        History
      </a>

     
    
 
    </div>    
     <div class="late_tasks_action" onclick="document.getElementById('late_tasks_modal').style.display='block'">
        {% if late_tasks.count == 1 %}
        <img src="{% static 'exclamation.png' %}" style="width: 13%;">
        ({{late_tasks.count}}) late task
        {% elif late_tasks.count > 1 %}
         <img src="{% static 'exclamation.png' %}" style="width: 13%;">
        ({{late_tasks.count}}) late tasks
        
        {% endif %}
      </div>
               
</div>
 <div class="team_container1">


<div id="team_all_task_list">

      <div class="manage_all_task_list_container_title">
          <div class="manage_all_task_list_name_title">Task name</div>
            
          <div class="manage_all_task_list_date_title">Due date</div>

     </div>
     {% for task in tasks %}
     {% if not task.approved_by %}
     <a href="{% url 'dashboard:task_manage_update' task.id %}"> 
     <div class="manage_all_task_list_container">
               <div class="manage_all_task_list_name">{{task.name}} </div>
            
               <div class="manage_all_task_list_date {% if task.due_date < time %}
                  manage_all_task_list_date_late {% endif %}">{{task.due_date}}</div>
     </div>
     </a>
     {% endif %}
     {% endfor %}



</div>

<div class="team_tasks" id="team_tasks">



{% for member in team %}
<div class="team_member_rows">
<a href="{% url 'dashboard:perf_detail' member.id %}" class="team_name_container">{{member.user.username}} ({{member.role.name}})</a>
{% for task in member.task_users.all %}
{% if not task.approved_by %}
{% if task.completed %}
<div class="tasks_units_blocks_completed">
      <a class="link_management" href="{% url 'dashboard:task_manage_update' task.id %}">
         {{task.name}}
         </a>

         <div class="icons_manage">
              <div class="people_img_div_man">
            {{count}}
               
            <img src="{% static 'team_icon14.png' %}" class="people_img" id="people{{task.id}}"
            data-member="{{task|get_team}}">
            </div>
          
            {% if task.section %}
            
            <div class="chart_icon_div_man"> 
            <img src="{% static 'chart_icon4.png' %}" id="chart_img{{task.id}}" class="chart_img"
                  onclick="info('{{task.chart.id}}')"
                   data-title="{{task.chart.title}}">
            </div>
            {% endif %}

         </div>


</div>


{% elif task.due_date < time  %}
 {% with task|getUserCount as count %}
<div class="tasks_units_blocks_denied">
         <a class="link_management" href="{% url 'dashboard:task_manage_update' task.id %}">
            {{task.name}}
         </a>
         <div class="icons_manage">
            <div class="people_img_div_man">
            {{count}}
               
            <img src="{% static 'team_icon14.png' %}" class="people_img" id="people{{task.id}}"
            data-member="{{task|get_team}}">
            </div>
           
            {% if task.section %}
            
            <div class="chart_icon_div_man"> 
            <img src="{% static 'chart_icon4.png' %}" id="chart_img{{task.id}}" class="chart_img"
                  onclick="info('{{task.chart.title}}')"
                  data-title="{{task.chart.title}}">
            </div>
            
            {% endif %}
          
         </div>
</div>
{% endwith %}
{% elif not task.completed %}
 {% with task|getUserCount as count %}
<div class="tasks_units_blocks">
     
         <a class="link_management" href="{% url 'dashboard:task_manage_update' task.id %}">
         {{task.name}}
         </a>

         <div class="icons_manage">
              <div class="people_img_div_man">
            {{count}}
               
            <img src="{% static 'team_icon14.png' %}" class="people_img" id="people{{task.id}}"
            data-member="{{task|get_team}}">
            </div>
          
            {% if task.section %}
            
            <div class="chart_icon_div_man"> 
            <img src="{% static 'chart_icon4.png' %}" id="chart_img{{task.id}}" class="chart_img"
                  onclick="info('{{task.chart.id}}')"
                   data-title="{{task.chart.title}}">
            </div>
            {% endif %}

         </div>
</div>

{% endwith %}

{% endif %}

{% endif %}
{% endfor %}
</div>
{% endfor %}




</div> 


<div class="team_management" id="team_buttons"> 



<div class="btn-div">  
 <a href="{% url 'dashboard:task_manage_create' %}"> 
    <button class="button_tasks_list" type="button">New task</button>
 </a>
</div>

<div class="btn-div3">
<a href="{% url 'dashboard:team_completed' %}"> 
<button class="button_tasks_list">Review tasks <span class="count_green">({{ count }})</span></button>
</a>   
</div>





<div class="btn-div2">
<a href="{% url 'dashboard:team_update' user.userprofile.team.id %}">
<button type="button" class="button_tasks_list">Pin a message</button>
</a>
</div>

<div class="btn-div-5">
   <a href="{% url 'dashboard:schedule_manage' %}"><button type="button" class="button_tasks_list">Schedules </button>
</a>

</div>

<div class="btn_div_6">
   <a href="{% url 'dashboard:perf_team' user.userprofile.team.id %}"> <button class="button_tasks_list"> Performance metrics</button></a>

</div>

<div class="btn_div_6">
  
      <button class="button_tasks_list"
      onclick="setVisibleFlex(null, 'reports_modal')">View reports<span class="count_green"> 
         ({{ unseen_reports }})</span></button>

</div>

</div>
 {% endif %}


 <div class="team_status_div 
 {% if user.userprofile.team.team_lead == user.userprofile %} 
 status_div_manage {% endif %}" id="team_status">
   {% for user in team %}
   {% with user.id|get_picture as id %}
   <div class="team_member_bubbles">
      <div class="username_div">
       {{user.user.username}}

       <div class="picture_cont">
         <img src="{% url 'dashboard:pic_picture' id %}" class="pic">

      </div>
      </div>
    
      
        <div class="active_task">
         <img src="{% static 'task_icon.png' %}" style="width: 7%;"> {{user.active_task.name}}
      </div>
      <div class="status">
         {{user.status}}
      </div>
      <div class="last_login">
        Last login : {{user.user.last_login}}
      </div>
     
   </div>
   {% endwith %}
   {% endfor %}
      
 </div>

</div>


       <div id="info_modal_team">
         <div class="team_list_title">
             Team

         </div>
         <div id="text_team"></div>
          
       </div>
         



      <div id="info_modal">
         
         <p id="text_value">
            Go to chart

         </p>
         </div>


<div id="reports_modal">
    <div class="x_btn_reports" 
     onclick="document.getElementById('reports_modal').style.display='none'">
      X
    </div>
      {% for report in reports %}
      {% if report.read %}
    <a href="{% url 'dashboard:get_report' report.id %}" class="seen_report">
     {{report.file_name}}

    </a>
    {% else %}
       <a href="{% url 'dashboard:get_report' report.id %}" class="new_report">
     {{report.file_name}}

    </a>
    {% endif %}
 
      {% endfor %}
</div>

<div class="late_tasks_modal" id="late_tasks_modal">
  <div class="x_div_late">
        <button class="x_btn_late" style="cursor: pointer;" 
        onclick="document.getElementById('late_tasks_modal').style.display='none'">
          X
        </button>
  </div>
   {% for task in late_tasks %}
    <a href="{% url 'dashboard:task_manage_update' task.id %}"> 
        <div class="late_task_unit_modal">
        {{task.name}}
         <div class="was_due"> Was due : {{task.due_date}}</div>
        </div>
    </a>
   {% endfor %}
</div>



<script>
$(document).ready(function() {
  $('#role').select2({
    placeholder: 'Filter by role',
  });
});


document.addEventListener('DOMContentLoaded', () => {
    setInfoBubble('chart_img', 'info_modal');
    setTeamBubble();
});


 function scrollToBot(elem1, elem2) {
  const div1 = document.getElementById(elem1);
  const div2 = document.getElementById(elem2);

  if (div1) {
    div1.scrollTo({
      top: div1.scrollHeight,
      behavior: 'smooth'
    });
  }

  if (div2) {
    div2.scrollTo({
      top: div2.scrollHeight,
    
      behavior: 'smooth'
    });
  }
}
  function scrollRight(elem) {
     const div = document.getElementById(elem);
 
    div.scrollTo({
      left: div.scrollWidth,
      behavior: 'smooth' 
      
    });
 
  }

function reset(elem1, elem2) {
  const div1 = document.getElementById(elem1);
  const div2 = document.getElementById(elem2);

  if (div1) {
    div1.scrollTo({
      top: 0,
      left: 0,
      behavior: 'smooth'
    });
  }

  if (div2) {
    div2.scrollTo({
      top: 0,
      left: 0,
      behavior: 'smooth'
    });
  }
}
</script>






 {% endblock %}