app/api/urls.py
from django.urls import path
from . import views
from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView
from django.urls import path, include
from	rest_framework.routers import	DefaultRouter


router = DefaultRouter()
from api.views import MessageViewSet, TaskViewSet,TeamViewSet, UserProfileViewSet
router.register("messages", MessageViewSet)
router.register('tasks', TaskViewSet)
router.register('team', TeamViewSet)


urlpatterns = [

     path("jwt/", TokenObtainPairView.as_view(), name="jwt_obtain_pair"),
     path("jwt/refresh/", TokenRefreshView.as_view(), name="jwt_refresh"),
     path('checkAuth/', views.checkAuth.as_view({'get': 'get'}), name='checkAuth'),
     path("home/", views.Homeview.as_view({'get': 'retrieve'}), name="home"),
     path('team/', views.TeamViewSet.as_view({'get':'list'}), name ='team'),
     path('activate/task/<int:pk>', views.ActivateTask.as_view(),name='activate'),
     path('subtasks/<int:pk>/', views.SubtaskViewSet.as_view({
                                     'post':'create', 'patch':'update'}), name="subtasks"),

     path('subtasks/completed/<int:pk>/', views.SubtaskCompleted, name="subtask_completed"),
     path('upload/', views.ImageUploadView.as_view(), name='upload'),
     path('upload/file/<int:pk>', views.FileUploadView.as_view(), name='uploadFiles'),
     path('chat/', views.ChatViewSet.as_view({'get':'get'}), name='chat'),
     path('chat/submit/', views.SaveMessage.as_view({'post':'post'}), name='savemsg'),
     path('loading/<str:celery_id>/<str:photo>/', views.Ready.as_view({'get': 'get'}), 
          name='ready'),
    # path('messages/unread', views.UnreadMessages.as_view(), name='unread_count'),
     path('profile/', views.UserProfileViewSet.as_view({'get':'retrieve'})),
     path('pushtoken/', views.RegisterPush.as_view(), name='registerpush'),
     path("",	include(router.urls)),

     #path('home')
]

app/dashboard/urls.py
from . import views
from django.urls import path
from .forms import CustomPasswordChangeForm, ProfileUpdateForm


app_name = 'dashboard'
urlpatterns = [
    
    ####### Users , Home#########
    path('options/', views.setOptions, name='options'),
    path('loading/<str:celery_id>/<str:type>/<int:object_id>/<str:arg>', 
         views.LoadingView.as_view(), name= 'loading'),
    path('loading/ready/<str:celery_id>/<str:type>/<int:object_id>/<str:arg>', 
         views.Ready, name='ready'),
         
    path('home/', views.BillboardView.as_view(), name = 'home'),
    path('logout/', views.LogoutView.as_view(), name ='logout'),
    path('report/', views.ReportView.as_view(), name='report'),
    path('role_dispatch/', views.role_dispatch, name='role_dispatch'),
    path('account/<int:pk>', views.AccountView.as_view(), name='user_account'),
    path('account/update/<int:pk>', views.AccountUpdate.as_view(form_class=ProfileUpdateForm),
     name='account_update'),
    path('account/update/password/<int:pk>', views.PasswordChangeView.as_view(
        form_class=CustomPasswordChangeForm), name="password_update"),
 
    ####### Messages ##########
    path('messages/reply/create/<int:recipient_id>', views.ReplyView.as_view(),
          name="message_reply"),
    path('messages/', views.HomeView.as_view(), name='messages'),
    path('messages/create/', views.MessageView.as_view(), name = 'messages_create'),
    path('messages/forward/<int:pk>', views.MessageForward.as_view(), name='message_forward'),
    path('report_detail/<int:id>/', views.MessageDetail.as_view(), name='reportview'),
    path('messages/inbox', views.InboxView.as_view(), name = 'inbox'),
    path('delete_report/<int:pk>', views.MessageDelete.as_view(), name = 'report_delete'),
    path('update_report/<int:pk>', views.MessageUpdate.as_view(), name = 'report_update'),
    ##########TASKS#########
    path('tasks/<int:pk>/activate', views.setActiveTask, name='activate_task'),
    path('tasks/subtask/<int:pk>', views.FetchSubtask, name='fetch_subtask'),
    path('tasks/<int:task>/subtask/<int:pk>', views.SubtaskCompleted, name="subtask_completed"),
    path('tasks/', views.TasksList.as_view(), name = 'tasks_list'),
    path('tasks/<int:pk>/', views.TaskDetail.as_view(), name='task_detail'),
    path('tasks/delete/<int:pk>', views.TaskDelete.as_view(), name = 'task_delete'),
    path('tasks/completed/<int:pk>', views.TaskSubmit.as_view(), name='task_submit'),
    ######### Files #########
    path('pic_picture/<int:pk>', views.stream_file, name='pic_picture'),
    path('pic_picture_completed_task/<int:pk>', views.stream_completed_task_img, 
         name='stream_completed_task_img'),
    path('file/<int:pk>/download', views.GetFile, name="get_file"),
    path('report/<int:pk>/download', views.getReport, name='get_report'),
    path('file/<int:pk>/task/delete/<int:manage>', views.DelFile, name='delete_file'),
    path('resource/<int:pk>', views.getResource, name='get_resource'),
    ####### MANAGE ###########
    path('team/', views.TeamView.as_view(), name = 'team'),
    path('tasks/completed/<int:pk>/', views.TaskCompletedDetail.as_view(), name='task_completed_detail'),
    path('tasks/create/', views.TaskManageCreate.as_view(), name = 'task_manage_create'),
    path('tasks/update/<int:pk>', views.TaskUpdate.as_view(), name = 'task_manage_update'),
    path('tasks/completed/approve/<int:pk>', views.TeamCompletedApprove.as_view(), 
         name = 'task_approve'),
    path('tasks/history/', views.TaskHistoryView.as_view(), name='task_history'),
    path('team/ressources', views.RessourcesView.as_view(), name="ressources"),
    path('team/getSection/<int:chart>', views.getSection, name='get_section'),



    ####### SCHEDULES ########
    path('schedules', views.ScheduleView.as_view(), name = 'schedule_view'),
    path('schedules/<int:pk>', views.ScheduleDetail.as_view(), name = 'schedule_detail'),
    path('schedules/manage', views.ScheduleManage.as_view(), name = 'schedule_manage'),
    path('schedules/update/<int:pk>', views.ScheduleUpdate.as_view(), 
         name = 'schedule_update'),
    path('schedules/user/<int:pk>/availability', views.AvailabilityForm.as_view(), 
         name='availability'),
    path('schedules/user/<int:pk>/request', views.ScheduleChangeRequest.as_view(),
          name='schedule_request'),
 
    #######TEAM ##########
    path('team/update/<int:pk>', views.TeamUpdate.as_view(), name='team_update'),
    path('team/completed/', views.TeamCompletedTask.as_view(), name='team_completed'),
    path('team/user/<int:pk>/stats', views.PerformanceDetail.as_view(), name = 'perf_detail'),
    path('team/<int:pk>/stats', views.PerformanceView.as_view(), name = 'perf_team'),
    path('team/<int:pk>/stats/page/<int:page>', views.PerformanceView.as_view(),
         name='perf_team_detail'),


    ####### Milestones ########
  
    path('history/milestones/team/<int:pk>', views.HistoryView.as_view(), name='history_view'),
    path('team/vs_team', views.TeamVs.as_view(), name="team_vs"),
    
    #######PROJECTS ######
    path('projects', views.ProjectsView.as_view(), name='projects'),
    path('projects/chart/<int:pk>', views.ChartDetail.as_view(), name='chart_detail'),
    path('projects/chart/create', views.ChartCreate.as_view(), name = "chart_create" ),
    path('projects/chart/load/<int:pk>', views.LoadChart, name="load_chart"),
    path('projects/chart/create/add_section/<int:pk>', views.AddSection.as_view(), name="add_section"),
    path('projects/chart/<int:pk>/create/task', views.ChartTaskCreate.as_view(),
          name='create_task_chart'),
    path('projects/chart/<int:chart>/task/<int:pk>/update', views.ChartTaskUpdate.as_view(), name='chart_task_update'),
    path('projects/chart/<int:pk>/update', views.ChartUpdate.as_view(), name='chart_update'),
    path('projects/chart/sections/delete/<int:pk>', views.SectionDelete, name='sections_update'),
    path('projects/chart/<int:pk>/delete', views.ChartDelete.as_view(), name ='chart_delete'),
    path('projects/chart/<int:pk>/reset', views.ChartReset, name='reset_chart'),
    #path('projects/chart/save/<int:pk>', views.SaveChart, name='chart_save'),
    path('projects/chart/<int:task_id>/<int:section_id>/<int:chart_id>/<str:prev>/<str:next>', 
         views.SwapTask, name='swapTask'),
    ######CHAT##########
    path('chat', views.ChatView.as_view(), name='chat_view'),
    path('chat/update/', views.ChatUpdate, name='chat_update'),

] 

app/portal/urls.py
from django.contrib import admin
from django.shortcuts import redirect
from django.urls import path, include, reverse
from dashboard.views import CustomLoginView
from dashboard.views import CustomRegistration
from dashboard.forms import CustomRegistrationForm
from django.conf.urls.static import	static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/' ,include('api.urls')),
    path('accounts/register/',
        CustomRegistration.as_view(form_class=CustomRegistrationForm),
        name='django_registration_register'),

    path("accounts/", include("django_registration.backends.one_step.urls")),
    path("accounts/", include("django.contrib.auth.urls")),
    path('dashboard/', include('dashboard.urls', namespace='dashboard')),
    path('', CustomLoginView.as_view(template_name='dashboard/login.html')),
    path('__debug__/', include('debug_toolbar.urls')),

]
urlpatterns+= static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns+= static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

app/dashboard/templates/dashboard/Projects/chart_body.html
{% load user_data %}
  {% for week in weeks %}
          
            {% with week_index=forloop.counter %}
           
            <div class="{{col_class}}">
                 
                   <div class="chart_col_right_top_row" id="source_number"> 
                   {{forloop.counter}} 
                   </div>
                    
                    {% for section in sections %}
                   <div class="chart_section_right"> 
             
                           {% for task in tasks_by_section|get_item:section.id %}
                         
                       
                           {% if user.userprofile.role.name == 'dev' %}
                           <div class="chart_right_task_row  {% if week_index < grey %} chart_right_task_row_grey {% elif week_index in grey_col_list %} chart_right_task_row_grey_alt {% endif %}"
                            id="right_rows{{task.id}}{{week_index}}" value="{{task.week}}"
                            onclick="Filltask('{{task.id}}', '{{week_index}}')">
                           </div>
                           {% else %}
                             <div class="chart_right_task_row_basic  {% if week_index < grey %} chart_right_task_row_grey {% elif week_index in grey_col_list %} chart_right_task_row_grey_alt {% endif %}"
                            id="right_rows{{task.id}}{{week_index}}" value="{{task.week}}"
                            onclick="Filltask('{{task.id}}', '{{week_index}}')">
                           </div>
                           {% endif %}
                    
                           {% endfor %}  
                             <div class="chart_right_task_row_grey"> </div>
                   </div>
                    {% endfor %}
                    
            
            {% endwith %}
            </div>
            {% endfor %}

app/dashboard/templates/dashboard/Projects/chart_confirm_delete.html
 {% include 'dashboard/base.html' %}

 {% block content %}
 <form method="post" class="single_title_form">
    {% csrf_token %}

     <p> Confirm deletion</p>
 <button class="button_chart_confirm_delete" type="submit">Delete</button>
 
  </form>
 <div class="send_msg_back">
   <button onclick="history.back()" class="del_btn2" type="button">Back</button>

 </div>
  {% endblock %}

app/dashboard/templates/dashboard/Projects/chart_create.html
 {% include 'dashboard/base.html' %}

 {% block content %}



<!--['name', 'description', 'urgent', 'due_date', 'users', 'completed']-->
          <form method="post" class="task_form">

<div class="form_container_chart_create">
      {% csrf_token %}
 
       <div class="title_chart_create_flex"> 
              <div class="forms"> {{ form.title.label_tag }}</div>
              <div>{{form.title}}</div>
       </div>

        <div class="flex_container_chart_create_top">
              <div>{{form.start_date.label_tag}}</div>
              <div >{{form.start_date}}</div>

        </div>


        <div class="flex_container_chart_create_top2">
    
              <div> {{form.end_date.label_tag}}</div>
              <div> {{form.end_date}}</div>
        </div>

        <div class="chart_create_select_div">
                        {{form.teams.label_tag}}
                        {{form.teams}}
                           {% if form.errors %}
           
                          <div style="height: 10%;">{{form.end_date.errors}}</div>
                   
            
                           {% endif %}
       </div> 




         <div>


         <input type="submit" name="send" value="Create" 
                          class="button_submit_new_section_form">


         </div>
              
                  
  </form>  

</div>
 

 <div class="send_msg_back">
   <button onclick="history.back()" class="del_btn2" type="button">Back</button></a>

 </div>
 
  


  {% endblock %}

app/dashboard/templates/dashboard/Projects/chart_form.html
 {% include 'dashboard/base.html' %}

 {% block content %}



<!--['name', 'description', 'urgent', 'due_date', 'users', 'completed']-->
          <form method="post" class="task_form">

<div class="form_container_chart_update">
      {% csrf_token %}
 
       <div class="title_chart_create_flex"> 
              <div class="forms"> {{ form.title.label_tag }}</div>
              <div>{{form.title}}</div>
       </div>

        <div class="flex_container_chart_create_top">
              <div>{{form.start_date.label_tag}}</div>
              <div >{{form.start_date}}</div>

        </div>
      

        <div class="flex_container_chart_create_top2">
    
              <div> {{form.end_date.label_tag}}</div>
              <div> {{form.end_date}}</div>
              
        </div>

        <div class="chart_create_select_div_mod">
                        {{form.teams.label_tag}}
                        {{form.teams}}
       </div>



      <div class="bot_flex_container_chart_create">

  

                  <div class="add_section_div_chart"> 
                         <div> Sections:</div>
                         <a href="{% url 'dashboard:add_section' chart.id %}">
                  
                         <input class="plus_sign_button_chart_create" value="+ Add sections"></input></a>
                 </div>
                
                   

      </div>
              
               
                
        <div class="sections_chart_update">

             {% for section in sections %}
            <a href="{% url 'dashboard:sections_update' section.id %}"> 
                  <div class="section_red_link">{{section}}</div>
             </a>  
            {% endfor %}
        </div>


         <div>


         <input type="submit" name="send" value="Submit" 
                          class="btn-submit-chart_update">


         </div>
              
                  
  </form>  

</div>
 

                <a href="{% url 'dashboard:chart_delete' chart.id %}">
                    <button class="chart_update_delete_btn">Delete chart</button> </a>
        
 <div class="send_msg_back">
   <button onclick="history.back()" class="del_btn2" type="button">Back</button></a>

 </div>
 

 {% if form.errors %}
           
                          <div style="height: 10%;">{{form.end_date.errors}}</div>
                   
            
                           {% endif %}

  {% endblock %}

app/dashboard/templates/dashboard/Projects/chart_task_create.html
 {% include 'dashboard/base.html' %}

 {% block content %}
 <div> 
<form method="post" class="task_form_chart" enctype="multipart/form-data">

<div class="form_container_create_task_chart">
      {% csrf_token %}

<div class="create_task_chart_name_div"> 
   <div class="create_task_chart_name_label"> {{ form.name.label_tag }}</div>
   <div class="form_margin" placeholder="text">{{form.name}}</div>
</div>

<div>  
  <div class="form_margin"> {{form.description.label_tag}}</div>
      <div class="task_create_chart_text_select"> 
    <div class="description_task_form_chart"> {{form.description}} </div>
      <div class="task_form_chart_select"> {{form.users}}</div>
      </div>
</div>


<div class="flex_form_container_chart_task">
 
   {{form.starting_date.label_tag}}
   {{form.starting_date}}

 <div>{{form.section.label_tag}}</div>
    <div>{{form.section}}</div>


   
         <div>

  
     </div>
    

</div>
<div class="due_date_chart_create">{{form.due_date.label_tag}}{{form.due_date}}</div> 
    
    <p> {{file_form.file_field}}   </p>
     {% if file_form.errors %}
     <div class="chart_task_form_error"> {{file_form.file_field.errors}}  </div>
      {% endif %} 
         <div class="chart_task_up_btn_div">

        <input type="submit" name="send" value="Submit" class="btn_submit_chart_task">
                    
    </div>

 </form>
</div>
  <div class="send_msg_back">
   <button onclick="history.back()" class="del_btn2" type="button">Back</button></a>

 </div>
  {% endblock %}

app/dashboard/templates/dashboard/Projects/chartsection_form.html
 {% include 'dashboard/base.html' %}

 {% block content %}
 <form method="post">
    {% csrf_token %}
{{form.as_p}}
     
 <button type="submit">Create</button>
 
  </form>

  {% endblock %}

app/dashboard/templates/dashboard/Projects/projects_view.html
 {% include 'dashboard/base.html' %}
{% load user_data %}
{% block extra_css %}
<style>
  body{
    overflow: hidden;
  }
</style>
{% endblock %}
 {% block content %}


<div class="create_chart_div">
     <div class="charts_title">
            <div class="outer_chart_title">
                 <div class="charts_title_text">
                  Charts 
                </div>
           </div>
    </div> 



     <div class="chart_create_new_chart"> 
    
             <div class="chart_create_chart_title">New chart
                {% if user.userprofile.role.name in allowed_roles %}
                   <a href="{% url 'dashboard:chart_create' %}"><button class="plus_sign_button">
                    +</button> </a>
                    {% if chart.id %}
                    <div class="save_modify_chart_btn_div">  
                       <button onclick="toggleGrid()" class="grid_btn"> Grid</button>
                         <button onclick="SaveChart('{{chart.id}}')" class="chart_save_btn">
                          Save</button> 
                         <a href="{% url 'dashboard:chart_update' chart.id %}">
                         <button class="chart_modify_button">Modify</button></a>
                             
                       
                               <a href="{% url 'dashboard:reset_chart' chart.id %}">
                               <button class="chart_clear_btn">Clear</button></a>
                         
                    </div>
                        
                    {% endif %}
                   {% endif %}
             </div>
             <div class="chart_create_buttons">
                    {% if not charts %}
                    <div style="
                    padding-left: 0.4%; 
                    padding-top: 0.4%;
                    font-size: small; 
                    display: flex;
                    align-items: baseline;"> 
                    No charts yet 
                  </div>
                    {% endif %}

                    {% for chart in charts %}     
                    
                    {% if forloop.counter < 5 %}
                    <a href="{% url 'dashboard:chart_detail' chart.id %}">
                     <button id="chart_btn_title{{chart.id}}" class="btn_title_chart" onclick="toggleButtons(this)"> 
                      {{chart.title}}</button></a>
                    {% if forloop.counter > 3 %}
                   
                    <div> 
                          <div> 
                         <button onclick="ShowDropdown()">...</button>
                         </div>
                         <div id="dropdown_charts"> 
                       
                                        
                     {% endif %}
                 
                    {% endif %}
                    {% endfor %}
                    {% for chart in charts %}
                    {% if forloop.counter > 4 %}
                       <a class="dropdown_links_charts" href="{% url 'dashboard:chart_detail' chart.id %}">
                            <button class="chart_dropdown_btn" 
                            id="chart_btn_title{{chart.id}}">{{chart.title}}</button></a>
                      {% endif %}
                      
                    {% endfor %}
                    </div>
                   </div>
             </div>
     </div>
</div>
    
 <div class="charts_container" id="charts_container">

     <div class="left_left_pane">

         
           

     </div>


     <div class="chart_left_pane"> 
            <div class="chart_left_title">
             Tasks
            </div>
            {% for section in sections %}
           
      <div class="name_section_wrapper_chart">
        <div class="chart_section_left_description_text">{{section.name}}  </div>
         <div class="chart_section_left" id="section_left">
                   {% for task in tasks_by_section|get_item:section.id %}
            
                      
                   <div class="chart_left_task_row
                   {% if task.submitted_at > task.due_date %} chart_left_task_row_late 
                   {% endif %}
                   " id="left_row{{task.id}}">

                    <a href="{% url 'dashboard:chart_task_update' chart.id task.id %}" 
                    class="task_name_div" id="task_name_div{{task.id}}">
                      
                     {{task.name}} 
                  
                      </a>

               <div class="arrows_div">
                    <a href="{% url 'dashboard:swapTask' task.id section.id chart.id 'true' 'false' %}">
                         <div id="up_arrow">
                           ▲
                         </div>
                    </a>

                    <a href="{% url 'dashboard:swapTask' task.id section.id chart.id 'false' 'true' %}">
                         <div id="down_arrow">▼
                         </div>
                    </a>


              </div>
                  
       </div>
                    
                
                    {% endfor %}

                   <a href="{% url 'dashboard:create_task_chart' chart.id %}">
                             
                      <div class="left_pane_add_task"> Add a task +

                      </div> </a>
                   

            </div></div>
                   {% endfor %}



                    {% if chart %}
                       {% if not sections %}
                       <a href="{% url 'dashboard:add_section' chart.id %}">
                             
                      <div class="left_pane_add_task_section"> Add a section +

                      </div> </a>
                      {% endif %}
                    {% if sections %}
                    {% if not chart.task_set %}
                    <a href="{% url 'dashboard:create_task_chart' chart.id %}">
                                      
                                <div class="left_pane_add_task"> Add a task +

                                </div> </a>
                    {% endif %}     
                    {% endif %}
                      {% endif %}
                  
     </div>
       
     <div class="chart_right_pane">
          <div class="chart_dates"> 
             {% if not months_list %}
             {% for month in chart.months %}
             
             <div class="one_date_container" id="months_cont"> 
      
            {{month}} 
             </div>
             {% endfor %}
             {% else %}
              {% for month in months_list %}
               <div class="one_date_container" id="months_cont"> 
      
            {{month}} 
             </div>
             {% endfor %}
              {% endif %}
          </div>

        <div class="right_chart_wrapper">
            <div class="right_row_description">
               
                   <div class="right_row_description_top_row"> 
                     Week
                   </div>

                    {% for section in sections %}
                   <div class="chart_section_right" id="source{{forloop.counter}}">
                           {% for task in tasks_by_section|get_item:section.id %}
                       
                           <div class="chart_right_task_row_grey">
                           </div>
                         
                           {% endfor %}  
                             <div class="chart_right_task_row_grey"></div>
                   </div>
                    {% endfor %}
            </div>
            
      
                {% with col_class="chart_col_right" %}
                  {% include "dashboard/projects/chart_body.html" %}
                {% endwith %}

         




     </div>
   </div>
 </div>

<script>
const chartStartDate = new Date('{{ chart.start_date|date:"Y-m-d" }}');
const now = new Date();

// Calculate difference in weeks
const diffInMs = now - chartStartDate;
const diffInWeeks = Math.floor(diffInMs / (1000 * 60 * 60 * 24 * 7));

const pxPerWeek = 26; // e.g., each week column is 50px wide
const offsetPx = diffInWeeks * pxPerWeek;

const container = document.getElementById('charts_container');
container.scrollLeft = offsetPx + 50;





const source = document.getElementById('source_number')
const targetDivs = document.querySelectorAll('.one_date_container');
const sourceWidth = window.getComputedStyle(source).width; 

const numericWidth = parseFloat(sourceWidth); // convert "100px" to 100

targetDivs.forEach(div => {
  div.style.width = `${(numericWidth + 3.6 ) * 4}px`;
});


// Filling the chart
let chart_data = {};

function toggleGrid(){
  const rows = document.querySelectorAll('.chart_right_task_row')

  rows.forEach(row => {
    const currentBorder = window.getComputedStyle(row).getPropertyValue('border-right');
    const currentBorderL = window.getComputedStyle(row).getPropertyValue('border-left');
    if (currentBorder.includes('rgba(0,0,0,0)') || currentBorder.includes('rgba(0, 0, 0, 0)')){
      row.style.borderRight = '2px solid rgb(63, 63, 63)';
      row.style.borderLeft = '2px solid rgb(63, 63, 63)';
    }
    else {
       row.style.borderRight = 'none';
       row.style.borderLeft = 'none';
    }
    
   
  });


}
function Filltask(n, cn) {
  
    const div = document.getElementById('right_rows'+ n + cn)

    let weeks = parseInt(div.getAttribute("value"));
    const currentColor = window.getComputedStyle(div).backgroundColor;

    if (weeks > 0 && currentColor !== 'rgb(173, 216, 230)') {
        div.style.backgroundColor = 'lightblue';
        weeks--;
        setRemainingClicks(n, weeks);

        if (!chart_data[n]) {
            chart_data[n] = []; 
    }

        chart_data[n].push(Number(cn))
       // console.log("Remaining clicks:", weeks);
      //  console.log(chart_data)
      }
      
      else if (weeks >= 0 && currentColor === 'rgb(173, 216, 230)'){
      div.style.backgroundColor = 'transparent';
      weeks ++;
      setRemainingClicks(n, weeks);
       chart_data[n] = chart_data[n].filter(item => item !== Number(cn));
       console.log("Type of cn:", typeof cn, "Value:", cn);

    }
      
      
      
      else {
        console.log("No more clicks allowed for this task.");
      }
    }


function setRemainingClicks(taskId, newValue) {
    const divs = document.querySelectorAll(`[id^="right_rows${taskId}"]`);

    divs.forEach(div => {
      div.setAttribute("value", newValue);
      //console.log(`Updated div: ${div.id}, Remaining clicks: ${newValue}`);
    });
  }


function SaveChart(n) {
    fetch(`http://127.0.0.1:8000/dashboard/projects/chart/${n}`, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      'X-CSRFToken': getCookie('csrftoken')  // If CSRF protection is enabled
    },
    body: JSON.stringify({ data: chart_data })
  });
}

function getCookie(name) {
  let cookieValue = null;
  if (document.cookie && document.cookie !== '') {
    const cookies = document.cookie.split(';');
    for (let i = 0; i < cookies.length; i++) {
      const cookie = cookies[i].trim();
      // Check if this cookie string begins with the name we want
      if (cookie.startsWith(name + '=')) {
        cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
        break;
      }
    }
  }
  return cookieValue;
}

const id = '{{chart.id}}'
const active_btn_id = "chart_btn_title"+ id
const active_button = document.getElementById(active_btn_id)
active_button.classList.toggle('active')

document.addEventListener('DOMContentLoaded', LoadChart());

async function LoadChart() {
  let chart_number = "{{ chart.id }}";

  try {
    const response = await fetch(`http://127.0.0.1:8000/dashboard/projects/chart/load/${chart_number}`);
    
    if (!response.ok) {
      throw new Error(`HTTP error! status: ${response.status}`);
    }

    const data_string = await response.json();
    const data = JSON.parse(data_string)
    //{"15": [4, 5, 6, 7], "26": [4, 5, 6, 3, 2]}

    for (const [key, value] of Object.entries(data)) {
       value.forEach(cn =>{ 
        Filltask(key, cn);
    });
    
 
}

  } catch (error) {
    console.error('Error fetching chart data:', error);
  }
  
     }
    

  function ShowDropdown(){
    const element = document.getElementById('dropdown_charts');
    if (element.style.display == 'none'){
      element.style.display = 'flex'
    }

    else{
           element.style.display = 'none';
    }
   

  }
 

document.querySelectorAll('[id^="left_row"]').forEach(row => {
  const arrowsDiv = row.querySelector('.arrows_div');

  row.addEventListener('mouseover', () => {
    if (arrowsDiv) arrowsDiv.style.display = 'block';
  });

  row.addEventListener('mouseout', () => {
    if (arrowsDiv) arrowsDiv.style.display = 'none';
  });
});
</script>
  {% endblock %}